# Copyright © Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier:  MIT

"""Provenance records for the checked-in code objects of one op and one arch.

Two artifacts, written by every generator run into the directory that holds the
objects (``<content>/<op>/<arch>/``):

* ``manifest.json`` -- the machine-readable record: the toolchain the objects
  were built with, and one row per instance (knobs, priority, symbol, kernarg
  layout, SHA256). The descriptor generator reads it; nothing else is a source
  of truth for what an object is.
* ``SOURCE.md`` -- the human-readable view of the same record, following the
  convention ``src/engines/asm_sdpa_engine/asm/asm_kernels/`` established for
  checked-in ``.co``: upstream source, toolchain, and a full SHA256 manifest.

A binary in the tree is only reviewable through these files, so a *stale* one is
worse than a missing one. ``refresh_source_md`` therefore rebuilds the document
from the manifest on every run rather than patching it.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

MANIFEST_NAME = "manifest.json"
MANIFEST_VERSION = 1


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def write_op_manifest(
    op_dir: Path, arch: str, op: str, provenance: dict, records: list[dict]
) -> Path:
    """Write ``<op_dir>/manifest.json`` for one generator run."""
    manifest = {
        "manifest_version": MANIFEST_VERSION,
        "arch": arch,
        "op": op,
        "toolchain": dict(provenance),
        "instances": records,
    }
    path = op_dir / MANIFEST_NAME
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(manifest, indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )
    return path


def refresh_source_md(op_dir: Path) -> Path:
    """Rebuild ``<op_dir>/SOURCE.md`` from the manifest beside it."""
    manifest_path = op_dir / MANIFEST_NAME
    if not manifest_path.is_file():
        raise FileNotFoundError(f"no {MANIFEST_NAME} in {op_dir}; nothing to describe")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    op = manifest["op"]
    arch = manifest["arch"]

    lines = [
        f"# FlyDSL AOT kernel objects — `{op}`, `{arch}`",
        "",
        "<!-- Generated by flydsl/generators/. Do not edit by hand: every generator",
        "     run rebuilds this file from manifest.json beside it. -->",
        "",
        f"{len(manifest['instances'])} checked-in code object(s), compiled from the "
        "vendored sources under",
        "`flydsl/kernels_src/` in the hip-kernel-provider tree. Regenerate with:",
        "",
        "```",
        f"python -m generators.gen_{op} --arch {arch}",
        "```",
        "",
        "run from `flydsl/`; see `flydsl/REGEN.md` for the environment.",
        "",
        "## Toolchain",
        "",
        "The toolchain is part of the artifact. Regenerating against a different FlyDSL",
        "or ROCm version is a *change* to these binaries, not a refresh, even when the",
        "instance list is untouched.",
        "",
        "| Component | Version |",
        "| --- | --- |",
    ]
    lines += [
        f"| {key} | `{value}` |" for key, value in manifest.get("toolchain", {}).items()
    ]
    lines += [
        "",
        "## Instances",
        "",
        "| Instance | Tier | Priority | Knobs | Symbol | Bytes |",
        "| --- | --- | ---: | --- | --- | ---: |",
    ]
    for record in manifest["instances"]:
        knobs = ", ".join(
            f"{key}={'runtime' if value is None else value}"
            for key, value in record["knobs"].items()
        )
        lines.append(
            f"| `{record['name']}` | {record['tier']} | {record['priority']} | "
            f"{knobs} | `{record['symbol']}` | {record['bytes']} |"
        )

    lines += ["", "## SHA256 manifest", "", "```"]
    for record in manifest["instances"]:
        lines.append(f"{record['sha256']}  {record['file']}")
    lines += ["```", ""]

    path = op_dir / "SOURCE.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
