// Automatically generated by scripts/gen_node_operands.py, do not modify.
//
// Per node type, a visitor over the node's operands, from the FlatBuffers schemas:
//
//   visitor.tensor(std::string_view role, int64_t uid, bool workDataDependent)
//     for every 'cache_uid' field present. The role is the field name
//     without '_tensor_uid' ('x_tensor_uid' -> "x"); a vector of uids reports
//     one call per element as "role[i]". An absent optional uid is skipped.
//     workDataDependent is the field's 'work_data_dependent' annotation: the
//     tensor's contents, not its shape, decide how much work the node does.
//   visitor.scalar(std::string_view name, int64_t | double | bool)
//     for every present scalar attribute that is not a tensor reference: integers
//     and enums as int64_t, floats as double, bools as bool. An absent optional
//     is skipped; a non-optional field reports its schema default when unset.
//   visitor.element(std::string_view name, size_t index, int64_t | double)
//     for every element of a numeric vector attribute (e.g. conv 'stride').
//
// Strings, nested tables and structs, unions and byte vectors (opaque payloads)
// are not visited. Operands are reported in schema declaration order. Reads the
// caller's buffer in place: no UnPack, no allocation, no reflection. Every
// std::string_view is valid only for the duration of the call.

#pragma once

#include <charconv>
#include <cstddef>
#include <cstdint>
#include <string_view>

#include <hipdnn_flatbuffers_sdk/data_objects/graph_generated.h>

namespace hipdnn_flatbuffers_sdk::data_objects::node_operands
{

namespace detail
{
/// "role[index]" formatted on the stack, so each element of a uid vector reaches
/// the visitor as its own role without allocating.
class IndexedRole
{
public:
    IndexedRole(std::string_view role, uint32_t index)
    {
        _size = role.copy(_text, role.size());
        _text[_size++] = '[';
        _size = static_cast<size_t>(
            std::to_chars(_text + _size, _text + sizeof(_text) - 1, index).ptr - _text);
        _text[_size++] = ']';
    }

    std::string_view view() const
    {
        return {_text, _size};
    }

private:
    // The longest vector role in the schema, '[', a uint32_t's ten digits, ']'.
    char _text[10 + 12] = {};
    size_t _size = 0;
};
} // namespace detail

/// Whether @p tensor's own fields make the work of every node reading or writing
/// it depend on tensor contents ('work_data_dependent' on a TensorAttributes field).
inline bool workDataDependent(const TensorAttributes& tensor)
{
    return tensor.ragged_offset_tensor_uid().has_value();
}

template <typename V>
void visit(const BatchnormInferenceAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("mean"), static_cast<int64_t>(op.mean_tensor_uid()), false);
    visitor.tensor(std::string_view("inv_variance"), static_cast<int64_t>(op.inv_variance_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    visitor.tensor(std::string_view("bias"), static_cast<int64_t>(op.bias_tensor_uid()), false);
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
}

template <typename V>
void visit(const PointwiseAttributes& op, V& visitor)
{
    visitor.scalar(std::string_view("operation"), static_cast<int64_t>(op.operation()));
    if(const auto value = op.relu_lower_clip(); value.has_value())
    {
        visitor.scalar(std::string_view("relu_lower_clip"), static_cast<double>(*value));
    }
    if(const auto value = op.relu_upper_clip(); value.has_value())
    {
        visitor.scalar(std::string_view("relu_upper_clip"), static_cast<double>(*value));
    }
    if(const auto value = op.relu_lower_clip_slope(); value.has_value())
    {
        visitor.scalar(std::string_view("relu_lower_clip_slope"), static_cast<double>(*value));
    }
    if(const auto value = op.axis_tensor_uid(); value.has_value())
    {
        visitor.scalar(std::string_view("axis_tensor_uid"), static_cast<int64_t>(*value));
    }
    visitor.tensor(std::string_view("in_0"), static_cast<int64_t>(op.in_0_tensor_uid()), false);
    if(const auto uid = op.in_1_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("in_1"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.in_2_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("in_2"), static_cast<int64_t>(*uid), false);
    }
    visitor.tensor(std::string_view("out_0"), static_cast<int64_t>(op.out_0_tensor_uid()), false);
    if(const auto value = op.swish_beta(); value.has_value())
    {
        visitor.scalar(std::string_view("swish_beta"), static_cast<double>(*value));
    }
    if(const auto value = op.elu_alpha(); value.has_value())
    {
        visitor.scalar(std::string_view("elu_alpha"), static_cast<double>(*value));
    }
    if(const auto value = op.softplus_beta(); value.has_value())
    {
        visitor.scalar(std::string_view("softplus_beta"), static_cast<double>(*value));
    }
}

template <typename V>
void visit(const BatchnormBackwardAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("dy"), static_cast<int64_t>(op.dy_tensor_uid()), false);
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    if(const auto uid = op.mean_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("mean"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.inv_variance_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("inv_variance"), static_cast<int64_t>(*uid), false);
    }
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    if(const auto* uids = op.peer_stats_tensor_uid())
    {
        for(uint32_t index = 0; index < uids->size(); ++index)
        {
            const detail::IndexedRole role("peer_stats", index);
            visitor.tensor(role.view(), static_cast<int64_t>(uids->Get(index)), false);
        }
    }
    visitor.tensor(std::string_view("dx"), static_cast<int64_t>(op.dx_tensor_uid()), false);
    visitor.tensor(std::string_view("dscale"), static_cast<int64_t>(op.dscale_tensor_uid()), false);
    visitor.tensor(std::string_view("dbias"), static_cast<int64_t>(op.dbias_tensor_uid()), false);
}

template <typename V>
void visit(const BatchnormAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    visitor.tensor(std::string_view("bias"), static_cast<int64_t>(op.bias_tensor_uid()), false);
    visitor.tensor(std::string_view("epsilon"), static_cast<int64_t>(op.epsilon_tensor_uid()), false);
    if(const auto* uids = op.peer_stats_tensor_uid())
    {
        for(uint32_t index = 0; index < uids->size(); ++index)
        {
            const detail::IndexedRole role("peer_stats", index);
            visitor.tensor(role.view(), static_cast<int64_t>(uids->Get(index)), false);
        }
    }
    if(const auto uid = op.prev_running_mean_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("prev_running_mean"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.prev_running_variance_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("prev_running_variance"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.momentum_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("momentum"), static_cast<int64_t>(*uid), false);
    }
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
    if(const auto uid = op.mean_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("mean"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.inv_variance_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("inv_variance"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.next_running_mean_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("next_running_mean"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.next_running_variance_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("next_running_variance"), static_cast<int64_t>(*uid), false);
    }
}

template <typename V>
void visit(const ConvolutionFwdAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("w"), static_cast<int64_t>(op.w_tensor_uid()), false);
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
    if(const auto* values = op.pre_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("pre_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.post_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("post_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.stride())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("stride"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.dilation())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("dilation"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    visitor.scalar(std::string_view("conv_mode"), static_cast<int64_t>(op.conv_mode()));
}

template <typename V>
void visit(const ConvolutionBwdAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("dy"), static_cast<int64_t>(op.dy_tensor_uid()), false);
    visitor.tensor(std::string_view("w"), static_cast<int64_t>(op.w_tensor_uid()), false);
    visitor.tensor(std::string_view("dx"), static_cast<int64_t>(op.dx_tensor_uid()), false);
    if(const auto* values = op.pre_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("pre_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.post_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("post_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.stride())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("stride"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.dilation())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("dilation"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    visitor.scalar(std::string_view("conv_mode"), static_cast<int64_t>(op.conv_mode()));
}

template <typename V>
void visit(const ConvolutionWrwAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("dy"), static_cast<int64_t>(op.dy_tensor_uid()), false);
    visitor.tensor(std::string_view("dw"), static_cast<int64_t>(op.dw_tensor_uid()), false);
    if(const auto* values = op.pre_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("pre_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.post_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("post_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.stride())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("stride"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.dilation())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("dilation"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    visitor.scalar(std::string_view("conv_mode"), static_cast<int64_t>(op.conv_mode()));
}

template <typename V>
void visit(const BatchnormInferenceAttributesVarianceExt& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("mean"), static_cast<int64_t>(op.mean_tensor_uid()), false);
    visitor.tensor(std::string_view("variance"), static_cast<int64_t>(op.variance_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    visitor.tensor(std::string_view("bias"), static_cast<int64_t>(op.bias_tensor_uid()), false);
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
    visitor.tensor(std::string_view("epsilon"), static_cast<int64_t>(op.epsilon_tensor_uid()), false);
}

template <typename V>
void visit(const MatmulAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("a"), static_cast<int64_t>(op.a_tensor_uid()), false);
    visitor.tensor(std::string_view("b"), static_cast<int64_t>(op.b_tensor_uid()), false);
    visitor.tensor(std::string_view("c"), static_cast<int64_t>(op.c_tensor_uid()), false);
}

template <typename V>
void visit(const RMSNormAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    visitor.tensor(std::string_view("epsilon"), static_cast<int64_t>(op.epsilon_tensor_uid()), false);
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
    if(const auto uid = op.bias_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("bias"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.inv_rms_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("inv_rms"), static_cast<int64_t>(*uid), false);
    }
    visitor.scalar(std::string_view("forward_phase"), static_cast<int64_t>(op.forward_phase()));
}

template <typename V>
void visit(const LayernormAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    visitor.tensor(std::string_view("bias"), static_cast<int64_t>(op.bias_tensor_uid()), false);
    visitor.tensor(std::string_view("epsilon"), static_cast<int64_t>(op.epsilon_tensor_uid()), false);
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
    visitor.scalar(std::string_view("normalized_dim_count"), static_cast<int64_t>(op.normalized_dim_count()));
    if(const auto uid = op.mean_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("mean"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.inv_variance_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("inv_variance"), static_cast<int64_t>(*uid), false);
    }
    visitor.scalar(std::string_view("forward_phase"), static_cast<int64_t>(op.forward_phase()));
}

template <typename V>
void visit(const SdpaAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("q"), static_cast<int64_t>(op.q_tensor_uid()), false);
    visitor.tensor(std::string_view("k"), static_cast<int64_t>(op.k_tensor_uid()), false);
    visitor.tensor(std::string_view("v"), static_cast<int64_t>(op.v_tensor_uid()), false);
    visitor.tensor(std::string_view("o"), static_cast<int64_t>(op.o_tensor_uid()), false);
    if(const auto uid = op.attn_mask_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("attn_mask"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.scale_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("scale"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.seq_len_q_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("seq_len_q"), static_cast<int64_t>(*uid), true);
    }
    if(const auto uid = op.seq_len_kv_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("seq_len_kv"), static_cast<int64_t>(*uid), true);
    }
    if(const auto uid = op.seed_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("seed"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.offset_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("offset"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.dropout_mask_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("dropout_mask"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.dropout_scale_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("dropout_scale"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.page_table_k_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("page_table_k"), static_cast<int64_t>(*uid), true);
    }
    if(const auto uid = op.page_table_v_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("page_table_v"), static_cast<int64_t>(*uid), true);
    }
    if(const auto uid = op.block_mask_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("block_mask"), static_cast<int64_t>(*uid), true);
    }
    if(const auto uid = op.sink_token_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("sink_token"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.descale_q_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("descale_q"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.descale_k_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("descale_k"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.descale_v_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("descale_v"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.descale_s_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("descale_s"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.scale_s_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("scale_s"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.scale_o_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("scale_o"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.stats_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("stats"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.max_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("max"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.sum_exp_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("sum_exp"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.rng_dump_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("rng_dump"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.amax_s_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("amax_s"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.amax_o_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("amax_o"), static_cast<int64_t>(*uid), false);
    }
    if(const auto value = op.generate_stats(); value.has_value())
    {
        visitor.scalar(std::string_view("generate_stats"), static_cast<bool>(*value));
    }
    visitor.scalar(std::string_view("alibi_mask"), static_cast<bool>(op.alibi_mask()));
    visitor.scalar(std::string_view("padding_mask"), static_cast<bool>(op.padding_mask()));
    visitor.scalar(std::string_view("causal_mask"), static_cast<bool>(op.causal_mask()));
    visitor.scalar(std::string_view("causal_mask_bottom_right"), static_cast<bool>(op.causal_mask_bottom_right()));
    if(const auto value = op.dropout_probability(); value.has_value())
    {
        visitor.scalar(std::string_view("dropout_probability"), static_cast<double>(*value));
    }
    if(const auto value = op.attn_scale_value(); value.has_value())
    {
        visitor.scalar(std::string_view("attn_scale_value"), static_cast<double>(*value));
    }
    if(const auto value = op.left_bound(); value.has_value())
    {
        visitor.scalar(std::string_view("left_bound"), static_cast<int64_t>(*value));
    }
    if(const auto value = op.right_bound(); value.has_value())
    {
        visitor.scalar(std::string_view("right_bound"), static_cast<int64_t>(*value));
    }
    if(const auto value = op.max_seq_len_kv(); value.has_value())
    {
        visitor.scalar(std::string_view("max_seq_len_kv"), static_cast<int64_t>(*value));
    }
    visitor.scalar(std::string_view("diagonal_alignment"), static_cast<int64_t>(op.diagonal_alignment()));
    visitor.scalar(std::string_view("mma_core_mode"), static_cast<int64_t>(op.mma_core_mode()));
    visitor.scalar(std::string_view("implementation"), static_cast<int64_t>(op.implementation()));
}

template <typename V>
void visit(const BlockScaleDequantizeAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
    if(const auto* values = op.block_size())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("block_size"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    visitor.scalar(std::string_view("is_negative_scale"), static_cast<bool>(op.is_negative_scale()));
}

template <typename V>
void visit(const BlockScaleQuantizeAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    visitor.scalar(std::string_view("block_size"), static_cast<int64_t>(op.block_size()));
    if(const auto value = op.axis(); value.has_value())
    {
        visitor.scalar(std::string_view("axis"), static_cast<int64_t>(*value));
    }
    visitor.scalar(std::string_view("transpose"), static_cast<bool>(op.transpose()));
}

template <typename V>
void visit(const SdpaBackwardAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("q"), static_cast<int64_t>(op.q_tensor_uid()), false);
    visitor.tensor(std::string_view("k"), static_cast<int64_t>(op.k_tensor_uid()), false);
    visitor.tensor(std::string_view("v"), static_cast<int64_t>(op.v_tensor_uid()), false);
    visitor.tensor(std::string_view("o"), static_cast<int64_t>(op.o_tensor_uid()), false);
    visitor.tensor(std::string_view("do"), static_cast<int64_t>(op.do_tensor_uid()), false);
    visitor.tensor(std::string_view("stats"), static_cast<int64_t>(op.stats_tensor_uid()), false);
    visitor.tensor(std::string_view("dq"), static_cast<int64_t>(op.dq_tensor_uid()), false);
    visitor.tensor(std::string_view("dk"), static_cast<int64_t>(op.dk_tensor_uid()), false);
    visitor.tensor(std::string_view("dv"), static_cast<int64_t>(op.dv_tensor_uid()), false);
    if(const auto uid = op.scale_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("scale"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.attn_mask_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("attn_mask"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.seq_len_q_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("seq_len_q"), static_cast<int64_t>(*uid), true);
    }
    if(const auto uid = op.seq_len_kv_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("seq_len_kv"), static_cast<int64_t>(*uid), true);
    }
    if(const auto uid = op.seed_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("seed"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.offset_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("offset"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.dropout_mask_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("dropout_mask"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.dropout_scale_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("dropout_scale"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.dropout_scale_inv_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("dropout_scale_inv"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.dbias_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("dbias"), static_cast<int64_t>(*uid), false);
    }
    visitor.scalar(std::string_view("alibi_mask"), static_cast<bool>(op.alibi_mask()));
    visitor.scalar(std::string_view("padding_mask"), static_cast<bool>(op.padding_mask()));
    visitor.scalar(std::string_view("causal_mask"), static_cast<bool>(op.causal_mask()));
    visitor.scalar(std::string_view("causal_mask_bottom_right"), static_cast<bool>(op.causal_mask_bottom_right()));
    if(const auto value = op.dropout_probability(); value.has_value())
    {
        visitor.scalar(std::string_view("dropout_probability"), static_cast<double>(*value));
    }
    if(const auto value = op.attn_scale_value(); value.has_value())
    {
        visitor.scalar(std::string_view("attn_scale_value"), static_cast<double>(*value));
    }
    if(const auto value = op.left_bound(); value.has_value())
    {
        visitor.scalar(std::string_view("left_bound"), static_cast<int64_t>(*value));
    }
    if(const auto value = op.right_bound(); value.has_value())
    {
        visitor.scalar(std::string_view("right_bound"), static_cast<int64_t>(*value));
    }
    visitor.scalar(std::string_view("diagonal_alignment"), static_cast<int64_t>(op.diagonal_alignment()));
}

template <typename V>
void visit(const CustomOpAttributes& op, V& visitor)
{
    if(const auto* uids = op.input_tensor_uids())
    {
        for(uint32_t index = 0; index < uids->size(); ++index)
        {
            const detail::IndexedRole role("input", index);
            visitor.tensor(role.view(), static_cast<int64_t>(uids->Get(index)), false);
        }
    }
    if(const auto* uids = op.output_tensor_uids())
    {
        for(uint32_t index = 0; index < uids->size(); ++index)
        {
            const detail::IndexedRole role("output", index);
            visitor.tensor(role.view(), static_cast<int64_t>(uids->Get(index)), false);
        }
    }
}

template <typename V>
void visit(const RMSNormBackwardAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("dy"), static_cast<int64_t>(op.dy_tensor_uid()), false);
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    visitor.tensor(std::string_view("inv_rms"), static_cast<int64_t>(op.inv_rms_tensor_uid()), false);
    visitor.tensor(std::string_view("dx"), static_cast<int64_t>(op.dx_tensor_uid()), false);
    visitor.tensor(std::string_view("dscale"), static_cast<int64_t>(op.dscale_tensor_uid()), false);
    if(const auto uid = op.dbias_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("dbias"), static_cast<int64_t>(*uid), false);
    }
}

template <typename V>
void visit(const ReductionAttributes& op, V& visitor)
{
    visitor.scalar(std::string_view("mode"), static_cast<int64_t>(op.mode()));
    visitor.tensor(std::string_view("in"), static_cast<int64_t>(op.in_tensor_uid()), false);
    visitor.tensor(std::string_view("out"), static_cast<int64_t>(op.out_tensor_uid()), false);
    visitor.scalar(std::string_view("is_deterministic"), static_cast<bool>(op.is_deterministic()));
}

template <typename V>
void visit(const ResampleFwdAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("y"), static_cast<int64_t>(op.y_tensor_uid()), false);
    if(const auto uid = op.index_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("index"), static_cast<int64_t>(*uid), false);
    }
    if(const auto* values = op.pre_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("pre_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.post_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("post_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.stride())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("stride"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.window())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("window"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    visitor.scalar(std::string_view("resample_mode"), static_cast<int64_t>(op.resample_mode()));
    visitor.scalar(std::string_view("padding_mode"), static_cast<int64_t>(op.padding_mode()));
    if(const auto value = op.generate_index(); value.has_value())
    {
        visitor.scalar(std::string_view("generate_index"), static_cast<bool>(*value));
    }
}

template <typename V>
void visit(const LayernormBackwardAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("dy"), static_cast<int64_t>(op.dy_tensor_uid()), false);
    visitor.tensor(std::string_view("x"), static_cast<int64_t>(op.x_tensor_uid()), false);
    visitor.tensor(std::string_view("scale"), static_cast<int64_t>(op.scale_tensor_uid()), false);
    if(const auto uid = op.mean_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("mean"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.inv_variance_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("inv_variance"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.epsilon_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("epsilon"), static_cast<int64_t>(*uid), false);
    }
    visitor.tensor(std::string_view("dx"), static_cast<int64_t>(op.dx_tensor_uid()), false);
    visitor.tensor(std::string_view("dscale"), static_cast<int64_t>(op.dscale_tensor_uid()), false);
    visitor.tensor(std::string_view("dbias"), static_cast<int64_t>(op.dbias_tensor_uid()), false);
    visitor.scalar(std::string_view("normalized_dim_count"), static_cast<int64_t>(op.normalized_dim_count()));
}

template <typename V>
void visit(const ResampleBwdAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("dy"), static_cast<int64_t>(op.dy_tensor_uid()), false);
    visitor.tensor(std::string_view("dx"), static_cast<int64_t>(op.dx_tensor_uid()), false);
    if(const auto uid = op.index_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("index"), static_cast<int64_t>(*uid), false);
    }
    if(const auto* values = op.pre_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("pre_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.post_padding())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("post_padding"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.stride())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("stride"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    if(const auto* values = op.window())
    {
        for(uint32_t index = 0; index < values->size(); ++index)
        {
            visitor.element(std::string_view("window"), static_cast<size_t>(index), static_cast<int64_t>(values->Get(index)));
        }
    }
    visitor.scalar(std::string_view("resample_mode"), static_cast<int64_t>(op.resample_mode()));
    visitor.scalar(std::string_view("padding_mode"), static_cast<int64_t>(op.padding_mode()));
}

template <typename V>
void visit(const MoeGroupedMatmulAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("token"), static_cast<int64_t>(op.token_tensor_uid()), false);
    visitor.tensor(std::string_view("weight"), static_cast<int64_t>(op.weight_tensor_uid()), false);
    visitor.tensor(std::string_view("first_token_offset"), static_cast<int64_t>(op.first_token_offset_tensor_uid()), true);
    if(const auto uid = op.token_index_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("token_index"), static_cast<int64_t>(*uid), false);
    }
    if(const auto uid = op.token_ks_tensor_uid(); uid.has_value())
    {
        visitor.tensor(std::string_view("token_ks"), static_cast<int64_t>(*uid), false);
    }
    visitor.tensor(std::string_view("output"), static_cast<int64_t>(op.output_tensor_uid()), false);
    visitor.scalar(std::string_view("mode"), static_cast<int64_t>(op.mode()));
    visitor.scalar(std::string_view("top_k"), static_cast<int64_t>(op.top_k()));
}

template <typename V>
void visit(const MoeGroupedMatmulBwdAttributes& op, V& visitor)
{
    visitor.tensor(std::string_view("doutput"), static_cast<int64_t>(op.doutput_tensor_uid()), false);
    visitor.tensor(std::string_view("token"), static_cast<int64_t>(op.token_tensor_uid()), false);
    visitor.tensor(std::string_view("first_token_offset"), static_cast<int64_t>(op.first_token_offset_tensor_uid()), true);
    visitor.tensor(std::string_view("dweight"), static_cast<int64_t>(op.dweight_tensor_uid()), false);
}

/// Visits @p node's operands. Returns false, visiting nothing, when the node has
/// no attributes or a type this header predates.
template <typename V>
bool visit(const Node& node, V&& visitor)
{
    // Fails when NodeAttributes gains a member this header has no case for: rerun
    // scripts/gen_node_operands.py.
    static_assert(NodeAttributes::MAX == NodeAttributes::MoeGroupedMatmulBwdAttributes,
                  "node_operands_generated.h is stale: rerun scripts/gen_node_operands.py");
    switch(node.attributes_type())
    {
    case NodeAttributes::BatchnormInferenceAttributes:
        if(const auto* op = node.attributes_as_BatchnormInferenceAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::PointwiseAttributes:
        if(const auto* op = node.attributes_as_PointwiseAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::BatchnormBackwardAttributes:
        if(const auto* op = node.attributes_as_BatchnormBackwardAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::BatchnormAttributes:
        if(const auto* op = node.attributes_as_BatchnormAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::ConvolutionFwdAttributes:
        if(const auto* op = node.attributes_as_ConvolutionFwdAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::ConvolutionBwdAttributes:
        if(const auto* op = node.attributes_as_ConvolutionBwdAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::ConvolutionWrwAttributes:
        if(const auto* op = node.attributes_as_ConvolutionWrwAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::BatchnormInferenceAttributesVarianceExt:
        if(const auto* op = node.attributes_as_BatchnormInferenceAttributesVarianceExt(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::MatmulAttributes:
        if(const auto* op = node.attributes_as_MatmulAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::RMSNormAttributes:
        if(const auto* op = node.attributes_as_RMSNormAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::LayernormAttributes:
        if(const auto* op = node.attributes_as_LayernormAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::SdpaAttributes:
        if(const auto* op = node.attributes_as_SdpaAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::BlockScaleDequantizeAttributes:
        if(const auto* op = node.attributes_as_BlockScaleDequantizeAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::BlockScaleQuantizeAttributes:
        if(const auto* op = node.attributes_as_BlockScaleQuantizeAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::SdpaBackwardAttributes:
        if(const auto* op = node.attributes_as_SdpaBackwardAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::CustomOpAttributes:
        if(const auto* op = node.attributes_as_CustomOpAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::RMSNormBackwardAttributes:
        if(const auto* op = node.attributes_as_RMSNormBackwardAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::ReductionAttributes:
        if(const auto* op = node.attributes_as_ReductionAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::ResampleFwdAttributes:
        if(const auto* op = node.attributes_as_ResampleFwdAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::LayernormBackwardAttributes:
        if(const auto* op = node.attributes_as_LayernormBackwardAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::ResampleBwdAttributes:
        if(const auto* op = node.attributes_as_ResampleBwdAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::MoeGroupedMatmulAttributes:
        if(const auto* op = node.attributes_as_MoeGroupedMatmulAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    case NodeAttributes::MoeGroupedMatmulBwdAttributes:
        if(const auto* op = node.attributes_as_MoeGroupedMatmulBwdAttributes(); op != nullptr)
        {
            visit(*op, visitor);
            return true;
        }
        return false;
    default:
        return false;
    }
}

} // namespace hipdnn_flatbuffers_sdk::data_objects::node_operands
