// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

// See graph.fbs for the semantics of these annotations.
attribute "cache_uid";
attribute "umd_opcode";
attribute "umd_input_tensor";
attribute "umd_output_tensor";
attribute "umd_name";

namespace hipdnn_flatbuffers_sdk.data_objects;

table BatchnormBackwardAttributes (umd_opcode: "batchnorm_bwd") {
    dy_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "dy");
    x_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "x");
    mean_tensor_uid: long = null (cache_uid, umd_input_tensor, umd_name: "mean");
    inv_variance_tensor_uid: long = null (cache_uid, umd_input_tensor, umd_name: "inv_variance");
    scale_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "scale");
    peer_stats_tensor_uid: [long] (cache_uid);
    dx_tensor_uid: long (cache_uid, umd_output_tensor, umd_name: "dx");
    dscale_tensor_uid: long (cache_uid, umd_output_tensor, umd_name: "dscale");
    dbias_tensor_uid: long (cache_uid, umd_output_tensor, umd_name: "dbias");
}
