// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

// See graph.fbs for the semantics of these annotations.
attribute "cache_uid";
attribute "umd_opcode";
attribute "umd_input_tensor";
attribute "umd_output_tensor";
attribute "umd_name";

namespace hipdnn_flatbuffers_sdk.data_objects;

// Note
// This is an additional version of batchnorm inference that uses a variance tensor
// instead of inv_variance tensor.

// The long attributes are keys to the tensor_attributes->uid
table BatchnormInferenceAttributesVarianceExt (umd_opcode: "batchnorm_inference_variance_ext") {
    x_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "x");
    mean_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "mean");
    variance_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "variance");
    scale_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "scale");
    bias_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "bias");
    y_tensor_uid: long (cache_uid, umd_output_tensor, umd_name: "y");
    epsilon_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "epsilon");
}
