// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

// See graph.fbs for the semantics of these annotations.
attribute "cache_uid";
attribute "umd_opcode";
attribute "umd_input_tensor";
attribute "umd_output_tensor";
attribute "umd_name";

namespace hipdnn_flatbuffers_sdk.data_objects;

table MoeGroupedMatmulBwdAttributes (umd_opcode: "moe_grouped_matmul_bwd") {
    // Required input tensor UIDs
    doutput_tensor_uid:            long (cache_uid, umd_input_tensor, umd_name: "doutput");
    token_tensor_uid:              long (cache_uid, umd_input_tensor, umd_name: "token");
    first_token_offset_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "first_token_offset");

    // Required output tensor UID
    dweight_tensor_uid:            long (cache_uid, umd_output_tensor, umd_name: "dweight");
}
