// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

include "norm_common.fbs";

// See graph.fbs for the semantics of these annotations.
attribute "cache_uid";
attribute "umd_opcode";
attribute "umd_input_tensor";
attribute "umd_output_tensor";
attribute "umd_name";

namespace hipdnn_flatbuffers_sdk.data_objects;

table RMSNormAttributes (umd_opcode: "rms_norm") {
    x_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "x");
    scale_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "scale");
    epsilon_tensor_uid: long (cache_uid, umd_input_tensor, umd_name: "epsilon");
    y_tensor_uid: long (cache_uid, umd_output_tensor, umd_name: "y");
    bias_tensor_uid: long = null (cache_uid, umd_input_tensor, umd_name: "bias");
    inv_rms_tensor_uid: long = null (cache_uid, umd_output_tensor, umd_name: "inv_rms");
    forward_phase: NormFwdPhase = NOT_SET;
}
