#!/usr/bin/env python3
# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Compile the gfx1151 decode kernel and attach Tensile's dispatch metadata."""
import argparse
from pathlib import Path
import subprocess
import tempfile

import yaml


CONFIG = {
    "InternalSupportParams": {
        "KernArgsVersion": 3,
        "UseUniversalArgs": True,
        "SupportUserGSU": False,
        "SupportCustomWGM": False,
        "SupportCustomStaggerU": False,
    },
    "WorkGroup": [4, 1, 32],
    "ThreadTile": [1, 1],
    "WavefrontSize": 32,
    "WaveSplitK": True,
    "DepthU": 256,
    "GlobalReadVectorWidthA": 8,
    "GlobalReadVectorWidthB": 1,
    "VectorWidthA": 1,
    "VectorWidthB": 1,
    "LocalReadVectorWidth": 2,
    "StoreVectorWidth": 1,
    "PrefetchGlobalRead": 1,
    "PrefetchLocalRead": 0,
    "ScheduleIterAlg": 0,
    "TransposeLDS": 2,
    "StaggerU": 0,
    "GlobalSplitU": 1,
    "WorkGroupMapping": 1,
    "AssertSummationElementMultiple": 256,
    "AssertSizeEqual": {1: 1, 2: 1},
    "AssertSizeGreaterThan": {3: 0},
}



def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", default="hipcc")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--group-size", type=int, choices=(32, 128), default=128)
    parser.add_argument("--load-width", type=int, choices=(4, 8), default=8)
    parser.add_argument("--unroll", type=int, choices=(1, 2, 4, 8), default=4)
    parser.add_argument("--accumulators", type=int, choices=(1, 4), default=1)
    parser.add_argument("--native-permute", action="store_true",
                        help="use compiler-native packed FP16 arithmetic and activation permutations")
    args = parser.parse_args()
    width_suffix = "_W4" if args.load_width == 4 else ""
    schedule_suffix = (f"_U{args.unroll}_A{args.accumulators}"
                       if (args.unroll, args.accumulators) != (4, 1) else "")
    if args.native_permute:
        schedule_suffix += "_NativePerm"
    name = f"Custom_W4A16_Decode_G{args.group_size}{width_suffix}{schedule_suffix}_UnsignedBias8_gfx1151"
    source = Path(__file__).resolve().parent / "w4a16_decode.hip"
    output = args.output or source.parent.parent / f"{name}.s"
    with tempfile.TemporaryDirectory() as directory:
        assembly = Path(directory) / "decode.s"
        subprocess.run(
            [args.compiler, "-O3", "--offload-arch=gfx1151", "-mcode-object-version=4",
             "-fuse-cuid=none", f"-DW4A16_GROUP_SIZE={args.group_size}",
             f"-DW4A16_KERNEL_NAME={name}", f"-DW4A16_LOAD_WIDTH={args.load_width}",
             f"-DW4A16_UNROLL={args.unroll}", f"-DW4A16_ACCUMULATORS={args.accumulators}",
             f"-DW4A16_NATIVE_PERMUTE={int(args.native_permute)}",
             "--cuda-device-only", "-S", str(source), "-o", str(assembly)],
            check=True,
        )
        text = assembly.read_text()
    # Keep the otherwise unused compiler marker unique when kernels share a code object.
    text = text.replace("__hip_cuid_", f"__hip_cuid_{name}")
    # Match the target spelling used by the custom-kernel inspection tools.
    text = text.replace(
        '\t.amdgcn_target "amdgcn-amd-amdhsa-unknown-gfx1151"',
        '.amdgcn_target "amdgcn-amd-amdhsa--gfx1151"',
    )
    assert text.count("\n---\n") == 1
    metadata = yaml.safe_dump({"custom.config": CONFIG}, sort_keys=False)
    text = text.replace("\n---\n", "\n---\n" + metadata)
    header = (
        "// Copyright Advanced Micro Devices, Inc., or its affiliates.\n"
        "// SPDX-License-Identifier: MIT\n"
        "// Generated by Source/generate_w4a16_decode.py from Source/w4a16_decode.hip.\n"
    )
    output.write_text(header + text)


if __name__ == "__main__":
    main()
