#!/usr/bin/env python3
# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Compile the gfx1151 decode kernel and attach Tensile's dispatch metadata."""
import argparse
from pathlib import Path
import subprocess
import tempfile

import yaml


CONFIG = {
    "InternalSupportParams": {
        "KernArgsVersion": 3,
        "UseUniversalArgs": True,
        "SupportUserGSU": False,
        "SupportCustomWGM": False,
        "SupportCustomStaggerU": False,
    },
    "WorkGroup": [4, 1, 32],
    "ThreadTile": [1, 1],
    "WavefrontSize": 32,
    "WaveSplitK": True,
    "DepthU": 256,
    "GlobalReadVectorWidthA": 8,
    "GlobalReadVectorWidthB": 1,
    "VectorWidthA": 1,
    "VectorWidthB": 1,
    "LocalReadVectorWidth": 2,
    "StoreVectorWidth": 1,
    "PrefetchGlobalRead": 1,
    "PrefetchLocalRead": 0,
    "ScheduleIterAlg": 0,
    "TransposeLDS": 2,
    "StaggerU": 0,
    "GlobalSplitU": 1,
    "WorkGroupMapping": 1,
    "AssertSummationElementMultiple": 256,
    "AssertSizeEqual": {1: 1, 2: 1},
    "AssertSizeGreaterThan": {3: 0},
}
NAME = "Custom_W4A16_Decode_G128_ExLlama_gfx1151"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", default="hipcc")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    source = Path(__file__).resolve().parent / "w4a16_decode.hip"
    output = args.output or source.parent.parent / f"{NAME}.s"
    with tempfile.TemporaryDirectory() as directory:
        assembly = Path(directory) / "decode.s"
        subprocess.run(
            [args.compiler, "-O3", "--offload-arch=gfx1151", "-mcode-object-version=4",
             "-fuse-cuid=none",
             "--cuda-device-only", "-S", str(source), "-o", str(assembly)],
            check=True,
        )
        text = assembly.read_text()
    # Match the target spelling used by the custom-kernel inspection tools.
    text = text.replace(
        '\t.amdgcn_target "amdgcn-amd-amdhsa-unknown-gfx1151"',
        '.amdgcn_target "amdgcn-amd-amdhsa--gfx1151"',
    )
    assert text.count("\n---\n") == 1
    metadata = yaml.safe_dump({"custom.config": CONFIG}, sort_keys=False)
    text = text.replace("\n---\n", "\n---\n" + metadata)
    header = (
        "// Copyright Advanced Micro Devices, Inc., or its affiliates.\n"
        "// SPDX-License-Identifier: MIT\n"
        "// Generated by Source/generate_w4a16_decode.py from Source/w4a16_decode.hip.\n"
    )
    output.write_text(header + text)


if __name__ == "__main__":
    main()
