# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_objects

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Layer 2 of a grouped model: the trees that rank candidates *within* one group.
#
# A grouped model answers two questions -- which group, then which candidate inside it --
# which is one question more than a single tree ensemble can express. MIOpen is the case
# that needs it (many solvers, each with its own perf-configs), but nothing here names an
# engine: a group is whatever value the grouping feature takes.
class GbdtGroup(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GbdtGroup()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGbdtGroup(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GbdtGroupBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x48\x47\x42\x4D", size_prefixed=size_prefixed)

    # GbdtGroup
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The grouping feature's value that selects this ensemble.
    # GbdtGroup
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Trees ranking candidates within this group. Same evaluation as GbdtModel.trees.
    # GbdtGroup
    def Trees(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from hipdnn_flatbuffers_sdk.data_objects.GbdtTree import GbdtTree
            obj = GbdtTree()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GbdtGroup
    def TreesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GbdtGroup
    def TreesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def GbdtGroupStart(builder):
    builder.StartObject(2)

def Start(builder):
    GbdtGroupStart(builder)

def GbdtGroupAddValue(builder, value):
    builder.PrependFloat64Slot(0, value, 0.0)

def AddValue(builder, value):
    GbdtGroupAddValue(builder, value)

def GbdtGroupAddTrees(builder, trees):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(trees), 0)

def AddTrees(builder, trees):
    GbdtGroupAddTrees(builder, trees)

def GbdtGroupStartTreesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTreesVector(builder, numElems):
    return GbdtGroupStartTreesVector(builder, numElems)

def GbdtGroupEnd(builder):
    return builder.EndObject()

def End(builder):
    return GbdtGroupEnd(builder)

import hipdnn_flatbuffers_sdk.data_objects.GbdtTree
try:
    from typing import List
except:
    pass

class GbdtGroupT(object):

    # GbdtGroupT
    def __init__(
        self,
        value = 0.0,
        trees = None,
    ):
        self.value = value  # type: float
        self.trees = trees  # type: Optional[List[hipdnn_flatbuffers_sdk.data_objects.GbdtTree.GbdtTreeT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        gbdtGroup = GbdtGroup()
        gbdtGroup.Init(buf, pos)
        return cls.InitFromObj(gbdtGroup)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, gbdtGroup):
        x = GbdtGroupT()
        x._UnPack(gbdtGroup)
        return x

    # GbdtGroupT
    def _UnPack(self, gbdtGroup):
        if gbdtGroup is None:
            return
        self.value = gbdtGroup.Value()
        if not gbdtGroup.TreesIsNone():
            self.trees = []
            for i in range(gbdtGroup.TreesLength()):
                if gbdtGroup.Trees(i) is None:
                    self.trees.append(None)
                else:
                    gbdtTree_ = hipdnn_flatbuffers_sdk.data_objects.GbdtTree.GbdtTreeT.InitFromObj(gbdtGroup.Trees(i))
                    self.trees.append(gbdtTree_)

    # GbdtGroupT
    def Pack(self, builder):
        if self.trees is not None:
            treeslist = []
            for i in range(len(self.trees)):
                treeslist.append(self.trees[i].Pack(builder))
            GbdtGroupStartTreesVector(builder, len(self.trees))
            for i in reversed(range(len(self.trees))):
                builder.PrependUOffsetTRelative(treeslist[i])
            trees = builder.EndVector()
        GbdtGroupStart(builder)
        GbdtGroupAddValue(builder, self.value)
        if self.trees is not None:
            GbdtGroupAddTrees(builder, trees)
        gbdtGroup = GbdtGroupEnd(builder)
        return gbdtGroup
