#!/usr/bin/env python3
# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
"""Regenerate the committed JIT test bundles in clients/tests/jit/data.

Runs the TensileLite generators with --source-only from this checkout, copies
each bundle without symbolic links, stores its library entry uncompressed,
removes the compiler path from its manifest and rewrites data/README.md. Run it
with the Python interpreter of a hipBLASLt build when the bundle freshness test
reports stale bundles.
"""

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import zlib

PROJECT = Path(__file__).resolve().parents[3]
TENSILE = PROJECT / "tensilelite"
DATA = Path(__file__).resolve().parent / "data"
FIXTURES = "Tensile/Tests/unit/test_data"
PROBLEM = "FP16 A, B, C and D, FP32 compute, A and B not transposed"

# name: (module, input relative to tensilelite, architecture, bundle within the
# output, problem the solution was generated for)
BUNDLES = {
    "splitk": (
        "Tensile.SingleSolution",
        f"{FIXTURES}/single_solution_splitk.yaml",
        "gfx950",
        "bundle",
        "M=256, N=128, K=512; GlobalSplitU=4 with MultipleBuffer, TileProcessingStrategy=None",
    ),
    "streamk": (
        "Tensile.SingleSolution",
        f"{FIXTURES}/single_solution_streamk.yaml",
        "gfx950",
        "bundle",
        "M=256, N=128, K=4096; TileProcessingStrategy=StreamK, WorkAssignment=StaticGrid,"
        " StreamKAtomic=0",
    ),
    "streamk-hybrid": (
        "Tensile.SingleSolution",
        f"{FIXTURES}/single_solution_streamk_hybrid.yaml",
        "gfx950",
        "bundle",
        "M=256, N=128, K=4096; TileProcessingStrategy=StreamK, WorkAssignment=Hybrid,"
        " WorkGroupMapping=0, WorkGroupMappingXCC=-1, as a Hybrid Stream-K candidate of the"
        " origami.gemm.persistent.v1 contract is compiled",
    ),
    "amax": (
        "Tensile.SingleSolution",
        f"{FIXTURES}/single_solution_amax.yaml",
        "gfx950",
        "bundle",
        "M=256, N=128, K=128; OutputAmaxD, GlobalSplitU=1, TileProcessingStrategy=None",
    ),
    "rank-1": (
        "Tensile.JitGemm",
        f"{FIXTURES}/jit_gemm_request_gfx950.json",
        "gfx950:sramecc+:xnack-",
        "bundle-0",
        "M=256, N=128, K=512; the first of two candidates Origami ranked for the"
        " origami.gemm.dp.v1 contract",
    ),
    "rank-2": (
        "Tensile.JitGemm",
        f"{FIXTURES}/jit_gemm_request_gfx950.json",
        "gfx950:sramecc+:xnack-",
        "bundle-1",
        "M=256, N=128, K=512; the second of those candidates",
    ),
}

README = """\
# Pre-generated JIT test bundles

Each directory under `gfx950/` is one source bundle: the input a JIT backend
returns and the comgr builder builds. The JIT tests replay these bundles
through the mock backend, so they need neither Python nor a generator.

| Path | Contents |
| --- | --- |
| `library/TensileLibrary.dat` | The one-solution library entry (MsgPack, uncompressed) |
| `sources/<kernel>.s` | The main kernel assembly; exactly one |
| `sources/Kernels.cpp`, `sources/Kernels.h` | Helper kernel source, when the solution needs helpers |
| Other `sources/*.h` files | Headers that `Kernels.cpp` includes |
| `manifest.json` | Provenance; hipBLASLt does not read it |

The manifest names the main kernel (`main_kernel.name`), the solution, the
library path and format, and the sources. Its `provenance` object records
`source_revision`, `generator_version`, `compiler_version`, `code_object_version`,
`kernargs_version` and `persistent_loop_args_version`.

All bundles target gfx950 and solve {problem}. The default
problem of the tests is M=256, N=128, K=512.

| Bundle | Problem and execution policy | Generator command |
| --- | --- | --- |
{rows}

The files are TensileLite output (MIT licence), generated by the commands above
from this repository's sources at each manifest's `source_revision`. Commands
run in `projects/hipblaslt/tensilelite` with `OUT` a fresh directory; the bundle
is the named directory under `OUT`.

## When the freshness test fails

The `jit-bundle-freshness` CTest test, `hipblaslt-jit-bundle-freshness-test`,
fails when a bundle's `kernargs_version` or `persistent_loop_args_version`
differs from `KernArgsVersion` or `PersistentLoopArgsVersion` in
`tensilelite/Tensile/Common/GlobalParameters.py`, when its `code_object_version`
differs from the version the JIT builder uses, or when the host library
cannot read its library entry or comgr cannot build its sources. The committed
bundles are then stale. Regenerate every bundle with the commands above, with
`PYTHONPATH` naming the `tensilelite/rocisa` and `tensilelite` directories of a
hipBLASLt build and then `projects/hipblaslt/tensilelite`. Copy each bundle
without symbolic links, inflate the generator's `library/TensileLibrary.dat.zlib`
into `library/TensileLibrary.dat` and point the manifest's `library.path` at it,
remove `provenance.compiler_path` from the manifest, update the bundle table,
and commit the bundles with the change that made them stale. No zlib-compressed
file is committed.
"""


def command(name):
    module, source, architecture, bundle, _ = BUNDLES[name]
    return (
        f"`python -m {module} {source} OUT --architecture {architecture}"
        f" --cxx-compiler amdclang++ --source-only` (`OUT/{bundle}`)"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", type=Path, required=True, help="hipBLASLt build with _rocisa")
    parser.add_argument(
        "--cxx-compiler",
        default=str(Path(os.environ.get("ROCM_PATH", "/opt/rocm")) / "bin/amdclang++"),
    )
    parser.add_argument("--scratch", type=Path, help="fresh directory for generator outputs")
    args = parser.parse_args()
    build = args.build.resolve(strict=True)
    scratch = args.scratch or Path(tempfile.mkdtemp(prefix="hipblaslt-jit-bundles-"))
    scratch.mkdir(parents=True, exist_ok=True)
    env = dict(
        os.environ,
        PYTHONPATH=os.pathsep.join(
            map(str, (build / "tensilelite/rocisa", build / "tensilelite", TENSILE))
        ),
        PYTHONDONTWRITEBYTECODE="1",
        TENSILE_DISABLE_HELPER_CACHE="1",
    )
    outputs = {}
    for name, (module, source, architecture, bundle, _) in BUNDLES.items():
        key = (module, source)
        if key not in outputs:
            output = scratch / name
            subprocess.run(
                [
                    sys.executable, "-m", module, str(TENSILE / source), str(output),
                    "--architecture", architecture, "--cxx-compiler", args.cxx_compiler,
                    "--source-only",
                ],
                cwd=TENSILE,
                env=env,
                check=True,
            )
            outputs[key] = output
        generated = (outputs[key] / bundle).resolve(strict=True)
        target = DATA / "gfx950" / name
        shutil.rmtree(target, ignore_errors=True)
        shutil.copytree(generated, target, symlinks=False)
        manifest = json.loads((target / "manifest.json").read_text())
        library = target / "library" / "TensileLibrary.dat"
        compressed = library.with_name(library.name + ".zlib")
        if compressed.exists():
            library.write_bytes(zlib.decompress(compressed.read_bytes()))
            compressed.unlink()
            manifest["library"]["path"] = "library/TensileLibrary.dat"
        manifest["provenance"].pop("compiler_path", None)
        (target / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
        assembly = list((target / "sources").glob("*.s"))
        if len(assembly) != 1 or any(path.is_symlink() for path in target.rglob("*")):
            raise RuntimeError(f"{name}: expected one .s file and no symbolic links")
        if any(path.suffix == ".zlib" for path in target.rglob("*")):
            raise RuntimeError(f"{name}: a zlib-compressed file would be committed")
        print(f"{name}: {manifest['main_kernel']['name']}")
    rows = "\n".join(
        f"| `gfx950/{name}` | {BUNDLES[name][4]} | {command(name)} |" for name in BUNDLES
    )
    (DATA / "README.md").write_text(README.format(problem=PROBLEM, rows=rows))


if __name__ == "__main__":
    main()
