// Copyright Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT
// Generated by Source/generate_w4a16_decode.py from Source/w4a16_decode.hip.
.amdgcn_target "amdgcn-amd-amdhsa--gfx1151"
	.amdhsa_code_object_version 4
	.text
	.protected	Custom_W4A16_Decode_G128_ExLlama_gfx1151 ; -- Begin function Custom_W4A16_Decode_G128_ExLlama_gfx1151
	.globl	Custom_W4A16_Decode_G128_ExLlama_gfx1151
	.p2align	8
	.type	Custom_W4A16_Decode_G128_ExLlama_gfx1151,@function
Custom_W4A16_Decode_G128_ExLlama_gfx1151: ; @Custom_W4A16_Decode_G128_ExLlama_gfx1151
	.cfi_startproc
; %bb.0:
	.cfi_escape 0x0f, 0x04, 0x30, 0x36, 0xe9, 0x02 ; CFA is 0 in private_wave aspace
	.cfi_undefined 16
	s_load_b32 s3, s[0:1], 0x10
	v_lshrrev_b32_e32 v7, 5, v0
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
	v_lshl_or_b32 v1, s2, 2, v7
	s_mov_b32 s2, exec_lo
	s_waitcnt lgkmcnt(0)
	v_cmpx_gt_u32_e32 s3, v1
	s_cbranch_execz .LBB0_22
; %bb.1:
	s_load_b64 s[8:9], s[0:1], 0x40
	v_and_b32_e32 v0, 31, v0
	s_waitcnt lgkmcnt(0)
	s_cmp_eq_f32 s8, 0
	s_cbranch_scc1 .LBB0_17
; %bb.2:
	s_clause 0x4
	s_load_b32 s3, s[0:1], 0x1c
	s_load_b32 s14, s[0:1], 0x30
	s_load_b128 s[4:7], s[0:1], 0x20
	s_load_b64 s[10:11], s[0:1], 0x68
	s_load_b64 s[12:13], s[0:1], 0x78
	s_waitcnt lgkmcnt(0)
	s_and_b32 s2, s3, 0x7ff
	s_and_b32 s15, s14, 63
	s_delay_alu instid0(SALU_CYCLE_1)
	s_or_b32 s2, s15, s2
	s_cbranch_scc0 .LBB0_7
; %bb.3:
	s_lshr_b32 s2, s3, 8
	v_lshrrev_b32_e32 v10, 1, v1
	s_cvt_f32_u32 s15, s2
	s_sub_i32 s16, 0, s2
	v_lshlrev_b32_e32 v12, 3, v0
	v_lshlrev_b32_e32 v13, 2, v7
	v_rcp_f32_e32 v2, s15
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(TRANS32_DEP_1)
	v_and_b32_e32 v13, 4, v13
	v_readfirstlane_b32 s15, v2
	s_mul_f32 s15, s15, 0x4f7ffffe
	s_delay_alu instid0(SALU_CYCLE_3) | instskip(NEXT) | instid1(SALU_CYCLE_3)
	s_cvt_u32_f32 s15, s15
	s_mul_i32 s16, s16, s15
	s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
	s_mul_hi_u32 s16, s15, s16
	s_add_i32 s15, s15, s16
	s_mov_b32 s16, 0
	v_mul_hi_u32 v2, v1, s15
	s_lshr_b32 s15, s14, 3
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_mul_lo_u32 v2, v2, s2
	v_sub_nc_u32_e32 v6, v1, v2
	v_mad_u64_u32 v[2:3], null, s15, v1, 0
	s_lshr_b32 s15, s3, 7
	s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(VALU_DEP_2)
	v_mad_u64_u32 v[4:5], null, s15, v1, 0
	v_subrev_nc_u32_e32 v8, s2, v6
	v_cmp_le_u32_e32 vcc_lo, s2, v6
	v_cndmask_b32_e32 v6, v6, v8, vcc_lo
	v_lshlrev_b64 v[8:9], 2, v[2:3]
	v_mad_u64_u32 v[2:3], null, s15, v10, s[12:13]
	v_lshlrev_b64 v[4:5], 1, v[4:5]
	s_bfe_u32 s15, s3, 0x20008
	v_subrev_nc_u32_e32 v10, s2, v6
	s_cmpk_lt_u32 s3, 0x400
	v_add_co_u32 v8, vcc_lo, s4, v8
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(VALU_DEP_1)
	v_add_co_ci_u32_e64 v9, null, s5, v9, vcc_lo
	v_cmp_le_u32_e32 vcc_lo, s2, v6
	v_cndmask_b32_e32 v6, v6, v10, vcc_lo
	v_add_co_u32 v10, vcc_lo, s10, v4
	v_add_co_ci_u32_e64 v11, null, s11, v5, vcc_lo
	s_delay_alu instid0(VALU_DEP_3)
	v_lshl_or_b32 v12, v6, 8, v12
	s_cbranch_scc1 .LBB0_8
; %bb.4:
	v_dual_mov_b32 v5, 0 :: v_dual_mov_b32 v6, 0
	s_and_b32 s16, s2, 0xfffffc
	s_mov_b32 s2, 0
	s_mov_b32 s17, 0xf000f
	s_mov_b32 s18, 0x10001
	s_mov_b32 s19, 0xf000f0
	s_mov_b32 s20, 0x100010
.LBB0_5:                                ; =>This Inner Loop Header: Depth=1
	v_lshl_add_u32 v4, s2, 8, v12
	s_add_i32 s2, s2, 4
	s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	s_cmp_eq_u32 s2, s16
	v_subrev_nc_u32_e32 v14, s3, v4
	v_add_nc_u32_e32 v16, 0x100, v4
	v_add_nc_u32_e32 v20, 0x200, v4
	v_add_nc_u32_e32 v28, 0x300, v4
	s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
	v_min_u32_e32 v4, v4, v14
	v_subrev_nc_u32_e32 v17, s3, v16
	s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
	v_subrev_nc_u32_e32 v21, s3, v20
	v_subrev_nc_u32_e32 v29, s3, v28
	s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
	v_lshrrev_b32_e32 v18, 1, v4
	v_lshrrev_b32_e32 v19, 7, v4
	v_lshlrev_b64 v[14:15], 1, v[4:5]
	v_min_u32_e32 v4, v16, v17
	v_and_b32_e32 v22, 0x7ffffffc, v18
	s_delay_alu instid0(VALU_DEP_4)
	v_add_co_u32 v16, vcc_lo, v2, v19
	v_lshlrev_b32_e32 v23, 1, v19
	v_add_co_ci_u32_e64 v17, null, 0, v3, vcc_lo
	v_lshrrev_b32_e32 v24, 1, v4
	v_add_co_u32 v14, vcc_lo, s6, v14
	v_lshrrev_b32_e32 v25, 7, v4
	v_lshlrev_b64 v[18:19], 1, v[4:5]
	v_min_u32_e32 v4, v20, v21
	v_add_co_ci_u32_e64 v15, null, s7, v15, vcc_lo
	v_add_co_u32 v20, vcc_lo, v8, v22
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_ci_u32_e64 v21, null, 0, v9, vcc_lo
	v_add_co_u32 v22, vcc_lo, v10, v23
	v_and_b32_e32 v30, 0x7ffffffc, v24
	v_add_co_ci_u32_e64 v23, null, 0, v11, vcc_lo
	v_add_co_u32 v24, vcc_lo, v2, v25
	v_lshlrev_b32_e32 v31, 1, v25
	v_add_co_ci_u32_e64 v25, null, 0, v3, vcc_lo
	v_lshrrev_b32_e32 v33, 1, v4
	v_add_co_u32 v18, vcc_lo, s6, v18
	v_lshrrev_b32_e32 v34, 7, v4
	v_lshlrev_b64 v[26:27], 1, v[4:5]
	v_add_co_ci_u32_e64 v19, null, s7, v19, vcc_lo
	global_load_b32 v35, v[20:21], off slc dlc
	global_load_u16 v36, v[22:23], off
	v_add_co_u32 v22, vcc_lo, v8, v30
	v_min_u32_e32 v4, v28, v29
	v_add_co_ci_u32_e64 v23, null, 0, v9, vcc_lo
	v_add_co_u32 v28, vcc_lo, v10, v31
	v_and_b32_e32 v33, 0x7ffffffc, v33
	s_clause 0x1
	global_load_u8 v32, v[16:17], off
	global_load_u8 v37, v[24:25], off
	v_add_co_ci_u32_e64 v29, null, 0, v11, vcc_lo
	v_add_co_u32 v24, vcc_lo, v2, v34
	v_lshlrev_b32_e32 v38, 1, v34
	v_add_co_ci_u32_e64 v25, null, 0, v3, vcc_lo
	v_add_co_u32 v26, vcc_lo, s6, v26
	v_lshrrev_b32_e32 v39, 7, v4
	v_lshrrev_b32_e32 v34, 1, v4
	v_lshlrev_b64 v[30:31], 1, v[4:5]
	v_add_co_ci_u32_e64 v27, null, s7, v27, vcc_lo
	global_load_b32 v4, v[22:23], off slc dlc
	global_load_u16 v40, v[28:29], off
	v_add_co_u32 v22, vcc_lo, v8, v33
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_add_co_ci_u32_e64 v23, null, 0, v9, vcc_lo
	v_add_co_u32 v28, vcc_lo, v10, v38
	v_add_co_ci_u32_e64 v29, null, 0, v11, vcc_lo
	global_load_u8 v33, v[24:25], off
	v_lshlrev_b32_e32 v38, 1, v39
	v_add_co_u32 v24, vcc_lo, v2, v39
	v_and_b32_e32 v34, 0x7ffffffc, v34
	v_add_co_ci_u32_e64 v25, null, 0, v3, vcc_lo
	v_add_co_u32 v30, vcc_lo, s6, v30
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_1)
	v_add_co_ci_u32_e64 v31, null, s7, v31, vcc_lo
	global_load_u16 v39, v[28:29], off
	global_load_b32 v41, v[22:23], off slc dlc
	global_load_u8 v42, v[24:25], off
	v_add_co_u32 v22, vcc_lo, v10, v38
	v_add_co_ci_u32_e64 v23, null, 0, v11, vcc_lo
	v_add_co_u32 v24, vcc_lo, v8, v34
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_ci_u32_e64 v25, null, 0, v9, vcc_lo
	global_load_u16 v34, v[22:23], off
	global_load_b32 v38, v[24:25], off slc dlc
	s_clause 0x3
	global_load_b128 v[22:25], v[26:27], off
	global_load_b128 v[26:29], v[30:31], off
	global_load_b128 v[14:17], v[14:15], off
	global_load_b128 v[18:21], v[18:19], off
	s_waitcnt vmcnt(14)
	v_lshl_or_b32 v31, v36, 16, v36
	v_lshrrev_b32_e32 v36, 8, v35
	s_delay_alu instid0(VALU_DEP_1)
	v_and_or_b32 v44, v36, s17, 0x64006400
	v_and_or_b32 v36, v36, s19, 0x54005400
	s_waitcnt vmcnt(13)
	v_bfe_u32 v30, v32, v13, 4
	s_waitcnt vmcnt(12)
	v_bfe_u32 v37, v37, v13, 4
	v_and_or_b32 v32, v35, s17, 0x64006400
	v_and_or_b32 v35, v35, s19, 0x54005400
	v_mad_u32_u24 v43, v30, s18, 0xe400e400
	;;#ASMSTART
	v_pk_add_f16 v45, v32, v43
	v_pk_mul_f16 v45, v45, v31
	;;#ASMEND
	s_waitcnt vmcnt(1)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v45, v14, v6
	;;#ASMEND
	v_mad_u32_u24 v30, v30, s20, 0xd400d400
	;;#ASMSTART
	v_pk_add_f16 v32, v35, v30
	v_pk_mul_f16 v32, v32, v31
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v32, v15, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v14, v44, v43
	v_pk_mul_f16 v14, v14, v31
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v14, v16, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v15, v36, v30
	v_pk_mul_f16 v15, v15, v31
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v15, v17, v6
	;;#ASMEND
	v_and_or_b32 v47, v4, s19, 0x54005400
	v_lshl_or_b32 v35, v40, 16, v40
	v_and_or_b32 v40, v4, s17, 0x64006400
	v_lshrrev_b32_e32 v4, 8, v4
	v_mad_u32_u24 v46, v37, s18, 0xe400e400
	;;#ASMSTART
	v_pk_add_f16 v31, v40, v46
	v_pk_mul_f16 v31, v31, v35
	;;#ASMEND
	s_waitcnt vmcnt(0)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v31, v18, v6
	;;#ASMEND
	v_mad_u32_u24 v37, v37, s20, 0xd400d400
	;;#ASMSTART
	v_pk_add_f16 v32, v47, v37
	v_pk_mul_f16 v32, v32, v35
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v32, v19, v6
	;;#ASMEND
	v_bfe_u32 v33, v33, v13, 4
	v_and_or_b32 v30, v4, s17, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v14, v30, v46
	v_pk_mul_f16 v14, v14, v35
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v14, v20, v6
	;;#ASMEND
	v_and_or_b32 v4, v4, s19, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v15, v4, v37
	v_pk_mul_f16 v15, v15, v35
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v15, v21, v6
	;;#ASMEND
	v_mad_u32_u24 v40, v33, s18, 0xe400e400
	v_mad_u32_u24 v33, v33, s20, 0xd400d400
	v_lshl_or_b32 v36, v39, 16, v39
	v_and_or_b32 v39, v41, s17, 0x64006400
	v_and_or_b32 v43, v41, s19, 0x54005400
	v_lshrrev_b32_e32 v41, 8, v41
	v_bfe_u32 v42, v42, v13, 4
	;;#ASMSTART
	v_pk_add_f16 v17, v39, v40
	v_pk_mul_f16 v17, v17, v36
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v17, v22, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v18, v43, v33
	v_pk_mul_f16 v18, v18, v36
	;;#ASMEND
	v_lshrrev_b32_e32 v35, 8, v38
	;;#ASMSTART
	v_dot2_f32_f16 v6, v18, v23, v6
	;;#ASMEND
	v_and_or_b32 v4, v41, s17, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v14, v4, v40
	v_pk_mul_f16 v14, v14, v36
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v14, v24, v6
	;;#ASMEND
	v_and_or_b32 v16, v41, s19, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v4, v16, v33
	v_pk_mul_f16 v4, v4, v36
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v4, v25, v6
	;;#ASMEND
	v_lshl_or_b32 v19, v34, 16, v34
	v_and_or_b32 v30, v38, s17, 0x64006400
	v_mad_u32_u24 v31, v42, s18, 0xe400e400
	;;#ASMSTART
	v_pk_add_f16 v17, v30, v31
	v_pk_mul_f16 v17, v17, v19
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v17, v26, v6
	;;#ASMEND
	v_and_or_b32 v32, v38, s19, 0x54005400
	v_mad_u32_u24 v34, v42, s20, 0xd400d400
	;;#ASMSTART
	v_pk_add_f16 v18, v32, v34
	v_pk_mul_f16 v18, v18, v19
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v18, v27, v6
	;;#ASMEND
	v_and_or_b32 v15, v35, s17, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v4, v15, v31
	v_pk_mul_f16 v4, v4, v19
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v4, v28, v6
	;;#ASMEND
	v_and_or_b32 v16, v35, s19, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v14, v16, v34
	v_pk_mul_f16 v14, v14, v19
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v14, v29, v6
	;;#ASMEND
	s_cbranch_scc0 .LBB0_5
; %bb.6:
	s_cmp_lg_u32 s15, 0
	s_cselect_b32 s2, -1, 0
	s_delay_alu instid0(SALU_CYCLE_1)
	s_and_b32 vcc_lo, exec_lo, s2
	s_cbranch_vccnz .LBB0_9
	s_branch .LBB0_11
.LBB0_7:
	s_mov_b32 s2, -1
                                        ; implicit-def: $vgpr6
	s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
	s_and_b32 s2, s2, exec_lo
	s_cselect_b32 s2, 1, 0
	s_cmp_lg_u32 s2, 1
	s_cbranch_scc0 .LBB0_12
	s_branch .LBB0_18
.LBB0_8:
	v_mov_b32_e32 v6, 0
	s_cbranch_execz .LBB0_11
.LBB0_9:
	v_mov_b32_e32 v5, 0
	s_mov_b32 s17, 0
	s_mov_b32 s18, 0xf000f
	s_mov_b32 s19, 0x10001
	s_mov_b32 s20, 0xf000f0
	s_mov_b32 s21, 0x100010
.LBB0_10:                               ; =>This Inner Loop Header: Depth=1
	v_lshl_add_u32 v4, s16, 8, v12
	s_add_i32 s17, s17, 1
	s_add_i32 s16, s16, 1
	s_cmp_lg_u32 s17, s15
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_subrev_nc_u32_e32 v14, s3, v4
	v_min_u32_e32 v4, v4, v14
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
	v_lshrrev_b32_e32 v17, 7, v4
	v_lshrrev_b32_e32 v16, 1, v4
	v_lshlrev_b64 v[14:15], 1, v[4:5]
	v_lshlrev_b32_e32 v18, 1, v17
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_and_b32_e32 v4, 0x7ffffffc, v16
	v_add_co_u32 v16, vcc_lo, v2, v17
	v_add_co_ci_u32_e64 v17, null, 0, v3, vcc_lo
	s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_add_co_u32 v18, s2, v10, v18
	v_add_co_ci_u32_e64 v19, null, 0, v11, s2
	v_add_co_u32 v20, s2, v8, v4
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_1)
	v_add_co_ci_u32_e64 v21, null, 0, v9, s2
	global_load_u8 v4, v[16:17], off
	global_load_u16 v18, v[18:19], off
	global_load_b32 v19, v[20:21], off slc dlc
	v_add_co_u32 v14, vcc_lo, s6, v14
	v_add_co_ci_u32_e64 v15, null, s7, v15, vcc_lo
	global_load_b128 v[14:17], v[14:15], off
	s_waitcnt vmcnt(3)
	v_bfe_u32 v4, v4, v13, 4
	s_waitcnt vmcnt(2)
	v_lshl_or_b32 v18, v18, 16, v18
	s_waitcnt vmcnt(1)
	v_lshrrev_b32_e32 v21, 8, v19
	v_and_or_b32 v20, v19, s18, 0x64006400
	v_and_or_b32 v19, v19, s20, 0x54005400
	v_mad_u32_u24 v22, v4, s19, 0xe400e400
	;;#ASMSTART
	v_pk_add_f16 v24, v20, v22
	v_pk_mul_f16 v24, v24, v18
	;;#ASMEND
	s_waitcnt vmcnt(0)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v24, v14, v6
	;;#ASMEND
	v_mad_u32_u24 v4, v4, s21, 0xd400d400
	;;#ASMSTART
	v_pk_add_f16 v20, v19, v4
	v_pk_mul_f16 v20, v20, v18
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v20, v15, v6
	;;#ASMEND
	v_and_or_b32 v23, v21, s18, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v14, v23, v22
	v_pk_mul_f16 v14, v14, v18
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v14, v16, v6
	;;#ASMEND
	v_and_or_b32 v21, v21, s20, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v15, v21, v4
	v_pk_mul_f16 v15, v15, v18
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v15, v17, v6
	;;#ASMEND
	s_cbranch_scc1 .LBB0_10
.LBB0_11:
	s_mov_b32 s2, 0
	s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
	s_and_b32 s2, s2, exec_lo
	s_cselect_b32 s2, 1, 0
	s_cmp_lg_u32 s2, 1
	s_cbranch_scc1 .LBB0_18
.LBB0_12:
	s_lshr_b32 s15, s3, 11
	s_mov_b32 s2, 0
	s_cbranch_scc0 .LBB0_17
; %bb.13:
	s_lshr_b32 s16, s3, 8
	s_lshr_b32 s14, s14, 3
	s_cvt_f32_u32 s17, s16
	s_sub_i32 s18, 0, s16
	v_lshrrev_b32_e32 v10, 1, v1
	v_lshlrev_b32_e32 v12, 2, v7
	v_rcp_f32_e32 v2, s17
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(TRANS32_DEP_1)
	v_and_b32_e32 v12, 4, v12
	v_readfirstlane_b32 s17, v2
	s_mul_f32 s17, s17, 0x4f7ffffe
	s_delay_alu instid0(SALU_CYCLE_3) | instskip(NEXT) | instid1(SALU_CYCLE_3)
	s_cvt_u32_f32 s17, s17
	s_mul_i32 s18, s18, s17
	s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
	s_mul_hi_u32 s18, s17, s18
	s_add_i32 s17, s17, s18
	s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_mul_hi_u32 v2, v1, s17
	v_mul_lo_u32 v2, v2, s16
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
	v_sub_nc_u32_e32 v6, v1, v2
	v_mad_u64_u32 v[2:3], null, s14, v1, 0
	s_lshr_b32 s14, s3, 7
	v_mad_u64_u32 v[4:5], null, s14, v1, 0
	v_subrev_nc_u32_e32 v8, s16, v6
	v_cmp_le_u32_e32 vcc_lo, s16, v6
	s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_4)
	v_cndmask_b32_e32 v6, v6, v8, vcc_lo
	v_lshlrev_b64 v[8:9], 2, v[2:3]
	v_mad_u64_u32 v[2:3], null, s14, v10, s[12:13]
	v_lshlrev_b64 v[4:5], 1, v[4:5]
	v_subrev_nc_u32_e32 v10, s16, v6
	s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_add_co_u32 v7, vcc_lo, s4, v8
	v_add_co_ci_u32_e64 v8, null, s5, v9, vcc_lo
	v_cmp_le_u32_e32 vcc_lo, s16, v6
	v_lshlrev_b32_e32 v11, 6, v0
	s_bfe_u32 s4, s3, 0x2000b
	s_cmpk_lt_u32 s3, 0x2000
	v_cndmask_b32_e32 v6, v6, v10, vcc_lo
	v_add_co_u32 v9, vcc_lo, s10, v4
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
	v_add_co_ci_u32_e64 v10, null, s11, v5, vcc_lo
	v_lshl_add_u32 v11, v6, 8, v11
	s_cbranch_scc1 .LBB0_23
; %bb.14:
	v_dual_mov_b32 v5, 0 :: v_dual_mov_b32 v6, 0
	s_and_b32 s2, s15, 0x1ffffc
	s_mov_b32 s5, 0
	s_mov_b32 s10, 0x10001
	s_mov_b32 s11, 0x100010
	s_mov_b32 s12, 0xf000f
	s_mov_b32 s13, 0xf000f0
.LBB0_15:                               ; =>This Inner Loop Header: Depth=1
	v_lshl_add_u32 v4, s5, 11, v11
	s_add_i32 s5, s5, 4
	s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	s_cmp_eq_u32 s5, s2
	v_subrev_nc_u32_e32 v13, s3, v4
	v_add_nc_u32_e32 v15, 0x800, v4
	v_add_nc_u32_e32 v17, 0x1000, v4
	v_add_nc_u32_e32 v18, 0x1800, v4
	s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
	v_min_u32_e32 v4, v4, v13
	v_subrev_nc_u32_e32 v16, s3, v15
	s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
	v_subrev_nc_u32_e32 v19, s3, v17
	v_subrev_nc_u32_e32 v20, s3, v18
	s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
	v_lshrrev_b32_e32 v21, 1, v4
	v_lshrrev_b32_e32 v22, 7, v4
	v_lshlrev_b64 v[13:14], 1, v[4:5]
	v_min_u32_e32 v4, v15, v16
	v_and_b32_e32 v21, 0x7ffffffc, v21
	s_delay_alu instid0(VALU_DEP_4)
	v_add_co_u32 v15, vcc_lo, v2, v22
	v_lshlrev_b32_e32 v23, 1, v22
	v_add_co_ci_u32_e64 v16, null, 0, v3, vcc_lo
	v_add_co_u32 v41, vcc_lo, s6, v13
	v_lshrrev_b32_e32 v24, 7, v4
	v_add_co_ci_u32_e64 v42, null, s7, v14, vcc_lo
	v_add_co_u32 v49, vcc_lo, v7, v21
	v_lshlrev_b64 v[45:46], 1, v[4:5]
	v_add_co_ci_u32_e64 v50, null, 0, v8, vcc_lo
	v_add_co_u32 v47, vcc_lo, v9, v23
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_1)
	v_add_co_ci_u32_e64 v48, null, 0, v10, vcc_lo
	v_add_co_u32 v53, vcc_lo, v2, v24
	global_load_u8 v71, v[15:16], off
	v_add_co_ci_u32_e64 v54, null, 0, v3, vcc_lo
	v_add_co_u32 v73, vcc_lo, s6, v45
	v_add_co_ci_u32_e64 v74, null, s7, v46, vcc_lo
	global_load_u16 v72, v[47:48], off
	s_clause 0x1
	global_load_b128 v[45:48], v[49:50], off slc dlc
	global_load_b128 v[49:52], v[49:50], off offset:16 slc dlc
	v_lshrrev_b32_e32 v22, 1, v4
	v_min_u32_e32 v4, v17, v19
	v_lshlrev_b32_e32 v56, 1, v24
	global_load_u8 v87, v[53:54], off
	v_and_b32_e32 v55, 0x7ffffffc, v22
	v_lshrrev_b32_e32 v57, 1, v4
	v_lshrrev_b32_e32 v58, 7, v4
	v_lshlrev_b64 v[69:70], 1, v[4:5]
	v_min_u32_e32 v4, v18, v20
	s_clause 0x7
	global_load_b128 v[13:16], v[41:42], off
	global_load_b128 v[17:20], v[41:42], off offset:16
	global_load_b128 v[21:24], v[41:42], off offset:32
	global_load_b128 v[25:28], v[41:42], off offset:48
	global_load_b128 v[29:32], v[41:42], off offset:64
	global_load_b128 v[33:36], v[41:42], off offset:80
	global_load_b128 v[37:40], v[41:42], off offset:96
	global_load_b128 v[41:44], v[41:42], off offset:112
	v_add_co_u32 v75, vcc_lo, v7, v55
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_1)
	v_add_co_ci_u32_e64 v76, null, 0, v8, vcc_lo
	v_lshrrev_b32_e32 v88, 1, v4
	v_lshrrev_b32_e32 v89, 7, v4
	v_lshlrev_b64 v[81:82], 1, v[4:5]
	v_add_co_u32 v77, vcc_lo, v9, v56
	v_add_co_ci_u32_e64 v78, null, 0, v10, vcc_lo
	v_add_co_u32 v79, vcc_lo, v2, v58
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_add_co_ci_u32_e64 v80, null, 0, v3, vcc_lo
	v_add_co_u32 v83, vcc_lo, s6, v69
	v_add_co_ci_u32_e64 v84, null, s7, v70, vcc_lo
	v_and_b32_e32 v85, 0x7ffffffc, v57
	v_lshlrev_b32_e32 v86, 1, v58
	s_clause 0x3
	global_load_b128 v[53:56], v[73:74], off
	global_load_b128 v[57:60], v[73:74], off offset:16
	global_load_b128 v[61:64], v[73:74], off offset:32
	global_load_b128 v[65:68], v[73:74], off offset:48
	v_and_b32_e32 v88, 0x7ffffffc, v88
	s_waitcnt vmcnt(16)
	v_bfe_u32 v4, v71, v12, 4
	s_waitcnt vmcnt(15)
	v_lshl_or_b32 v90, v72, 16, v72
	s_waitcnt vmcnt(14)
	v_lshrrev_b32_e32 v92, 8, v45
	v_mad_u32_u24 v91, v4, s10, 0xe400e400
	v_and_or_b32 v69, v45, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v71, v69, v91
	v_pk_mul_f16 v71, v71, v90
	;;#ASMEND
	s_waitcnt vmcnt(11)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v71, v13, v6
	;;#ASMEND
	v_mad_u32_u24 v4, v4, s11, 0xd400d400
	v_and_or_b32 v45, v45, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v69, v45, v4
	v_pk_mul_f16 v69, v69, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v69, v14, v6
	;;#ASMEND
	v_and_or_b32 v70, v92, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v13, v70, v91
	v_pk_mul_f16 v13, v13, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v13, v15, v6
	;;#ASMEND
	v_and_or_b32 v13, v92, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v14, v13, v4
	v_pk_mul_f16 v14, v14, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v14, v16, v6
	;;#ASMEND
	global_load_b128 v[13:16], v[73:74], off offset:80
	global_load_u16 v92, v[77:78], off
	v_and_or_b32 v45, v46, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v78, v45, v91
	v_pk_mul_f16 v78, v78, v90
	;;#ASMEND
	s_waitcnt vmcnt(12)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v78, v17, v6
	;;#ASMEND
	v_lshrrev_b32_e32 v17, 8, v46
	v_and_or_b32 v77, v46, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v45, v77, v4
	v_pk_mul_f16 v45, v45, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v45, v18, v6
	;;#ASMEND
	v_lshrrev_b32_e32 v77, 8, v47
	v_and_or_b32 v18, v17, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v45, v18, v91
	v_pk_mul_f16 v45, v45, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v45, v19, v6
	;;#ASMEND
	v_and_or_b32 v17, v17, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v18, v17, v4
	v_pk_mul_f16 v18, v18, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v18, v20, v6
	;;#ASMEND
	v_and_or_b32 v45, v47, s12, 0x64006400
	v_and_or_b32 v46, v47, s13, 0x54005400
	v_lshrrev_b32_e32 v94, 8, v48
	;;#ASMSTART
	v_pk_add_f16 v47, v45, v91
	v_pk_mul_f16 v47, v47, v90
	;;#ASMEND
	s_waitcnt vmcnt(11)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v47, v21, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v45, v46, v4
	v_pk_mul_f16 v45, v45, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v45, v22, v6
	;;#ASMEND
	v_and_or_b32 v21, v77, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v46, v21, v91
	v_pk_mul_f16 v46, v46, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v46, v23, v6
	;;#ASMEND
	v_and_or_b32 v21, v77, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v22, v21, v4
	v_pk_mul_f16 v22, v22, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v22, v24, v6
	;;#ASMEND
	v_and_or_b32 v78, v48, s12, 0x64006400
	v_and_or_b32 v93, v48, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v77, v78, v91
	v_pk_mul_f16 v77, v77, v90
	;;#ASMEND
	s_waitcnt vmcnt(10)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v77, v25, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v25, v93, v4
	v_pk_mul_f16 v25, v25, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v25, v26, v6
	;;#ASMEND
	v_and_or_b32 v25, v94, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v26, v25, v91
	v_pk_mul_f16 v26, v26, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v26, v27, v6
	;;#ASMEND
	v_and_or_b32 v25, v94, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v26, v25, v4
	v_pk_mul_f16 v26, v26, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v26, v28, v6
	;;#ASMEND
	v_lshrrev_b32_e32 v26, 8, v49
	v_and_or_b32 v25, v49, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v28, v25, v91
	v_pk_mul_f16 v28, v28, v90
	;;#ASMEND
	s_waitcnt vmcnt(9)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v28, v29, v6
	;;#ASMEND
	v_and_or_b32 v27, v49, s13, 0x54005400
	v_and_or_b32 v25, v26, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v28, v27, v4
	v_pk_mul_f16 v28, v28, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v28, v30, v6
	;;#ASMEND
	v_and_or_b32 v26, v26, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v27, v25, v91
	v_pk_mul_f16 v27, v27, v90
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v25, v26, v4
	v_pk_mul_f16 v25, v25, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v27, v31, v6
	;;#ASMEND
	s_clause 0x2
	global_load_b128 v[69:72], v[73:74], off offset:64
	global_load_b128 v[17:20], v[73:74], off offset:96
	global_load_b128 v[45:48], v[73:74], off offset:112
	;;#ASMSTART
	v_dot2_f32_f16 v6, v25, v32, v6
	;;#ASMEND
	global_load_b128 v[25:28], v[83:84], off
	global_load_b128 v[21:24], v[75:76], off slc dlc
	global_load_u8 v95, v[79:80], off
	global_load_b128 v[73:76], v[75:76], off offset:16 slc dlc
	v_lshrrev_b32_e32 v30, 8, v50
	v_and_or_b32 v29, v50, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v32, v29, v91
	v_pk_mul_f16 v32, v32, v90
	;;#ASMEND
	s_waitcnt vmcnt(15)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v32, v33, v6
	;;#ASMEND
	v_and_or_b32 v31, v50, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v32, v31, v4
	v_pk_mul_f16 v32, v32, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v32, v34, v6
	;;#ASMEND
	v_lshrrev_b32_e32 v34, 8, v51
	v_and_or_b32 v29, v30, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v31, v29, v91
	v_pk_mul_f16 v31, v31, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v31, v35, v6
	;;#ASMEND
	v_lshrrev_b32_e32 v49, 8, v52
	v_add_co_u32 v77, vcc_lo, v7, v85
	v_and_or_b32 v30, v30, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v29, v30, v4
	v_pk_mul_f16 v29, v29, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v29, v36, v6
	;;#ASMEND
	v_and_or_b32 v33, v51, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v36, v33, v91
	v_pk_mul_f16 v36, v36, v90
	;;#ASMEND
	s_waitcnt vmcnt(14)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v36, v37, v6
	;;#ASMEND
	v_add_co_ci_u32_e64 v78, null, 0, v8, vcc_lo
	v_add_co_u32 v79, vcc_lo, v9, v86
	v_and_or_b32 v35, v51, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v36, v35, v4
	v_pk_mul_f16 v36, v36, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v36, v38, v6
	;;#ASMEND
	v_and_or_b32 v33, v34, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v35, v33, v91
	v_pk_mul_f16 v35, v35, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v35, v39, v6
	;;#ASMEND
	v_add_co_ci_u32_e64 v80, null, 0, v10, vcc_lo
	v_lshlrev_b32_e32 v93, 1, v89
	v_add_co_u32 v85, vcc_lo, v2, v89
	v_and_or_b32 v34, v34, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v33, v34, v4
	v_pk_mul_f16 v33, v33, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v33, v40, v6
	;;#ASMEND
	v_and_or_b32 v37, v52, s12, 0x64006400
	v_and_or_b32 v50, v52, s13, 0x54005400
	v_and_or_b32 v38, v49, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v51, v37, v91
	v_pk_mul_f16 v51, v51, v90
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v89, v38, v91
	v_pk_mul_f16 v89, v89, v90
	;;#ASMEND
	v_and_or_b32 v49, v49, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v52, v50, v4
	v_pk_mul_f16 v52, v52, v90
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v91, v49, v4
	v_pk_mul_f16 v91, v91, v90
	;;#ASMEND
	v_bfe_u32 v4, v87, v12, 4
	s_waitcnt vmcnt(13)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v51, v41, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v52, v42, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v89, v43, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v91, v44, v6
	;;#ASMEND
	v_mad_u32_u24 v89, v4, s10, 0xe400e400
	v_mad_u32_u24 v4, v4, s11, 0xd400d400
	s_clause 0x3
	global_load_b128 v[29:32], v[83:84], off offset:16
	global_load_b128 v[33:36], v[83:84], off offset:32
	global_load_b128 v[37:40], v[83:84], off offset:48
	global_load_b128 v[49:52], v[83:84], off offset:64
	v_add_co_ci_u32_e64 v86, null, 0, v3, vcc_lo
	v_add_co_u32 v81, vcc_lo, s6, v81
	s_delay_alu instid0(VALU_DEP_1)
	v_add_co_ci_u32_e64 v82, null, s7, v82, vcc_lo
	global_load_u8 v85, v[85:86], off
	s_waitcnt vmcnt(12)
	v_lshl_or_b32 v90, v92, 16, v92
	s_waitcnt vmcnt(7)
	v_lshrrev_b32_e32 v87, 8, v21
	v_and_or_b32 v41, v21, s12, 0x64006400
	v_and_or_b32 v21, v21, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v43, v41, v89
	v_pk_mul_f16 v43, v43, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v43, v53, v6
	;;#ASMEND
	v_and_or_b32 v42, v87, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v41, v21, v4
	v_pk_mul_f16 v41, v41, v90
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v21, v42, v89
	v_pk_mul_f16 v21, v21, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v41, v54, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v21, v55, v6
	;;#ASMEND
	v_and_or_b32 v21, v87, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v53, v21, v4
	v_pk_mul_f16 v53, v53, v90
	;;#ASMEND
	v_lshrrev_b32_e32 v21, 8, v22
	;;#ASMSTART
	v_dot2_f32_f16 v6, v53, v56, v6
	;;#ASMEND
	v_and_or_b32 v53, v22, s12, 0x64006400
	v_and_or_b32 v22, v22, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v55, v53, v89
	v_pk_mul_f16 v55, v55, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v55, v57, v6
	;;#ASMEND
	v_and_or_b32 v54, v21, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v53, v22, v4
	v_pk_mul_f16 v53, v53, v90
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v22, v54, v89
	v_pk_mul_f16 v22, v22, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v53, v58, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v22, v59, v6
	;;#ASMEND
	v_and_or_b32 v21, v21, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v22, v21, v4
	v_pk_mul_f16 v22, v22, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v22, v60, v6
	;;#ASMEND
	v_lshrrev_b32_e32 v22, 8, v23
	s_clause 0x2
	global_load_b128 v[41:44], v[83:84], off offset:80
	global_load_b128 v[53:56], v[83:84], off offset:96
	global_load_b128 v[57:60], v[83:84], off offset:112
	v_and_or_b32 v21, v23, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v83, v21, v89
	v_pk_mul_f16 v83, v83, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v83, v61, v6
	;;#ASMEND
	v_and_or_b32 v23, v23, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v61, v23, v4
	v_pk_mul_f16 v61, v61, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v61, v62, v6
	;;#ASMEND
	v_and_or_b32 v21, v22, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v23, v21, v89
	v_pk_mul_f16 v23, v23, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v23, v63, v6
	;;#ASMEND
	v_and_or_b32 v22, v22, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v21, v22, v4
	v_pk_mul_f16 v21, v21, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v21, v64, v6
	;;#ASMEND
	global_load_b128 v[61:64], v[77:78], off slc dlc
	global_load_u16 v91, v[79:80], off
	global_load_b128 v[77:80], v[77:78], off offset:16 slc dlc
	v_lshrrev_b32_e32 v92, 8, v24
	v_and_or_b32 v21, v24, s12, 0x64006400
	v_and_or_b32 v22, v24, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v24, v21, v89
	v_pk_mul_f16 v24, v24, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v24, v65, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v21, v22, v4
	v_pk_mul_f16 v21, v21, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v21, v66, v6
	;;#ASMEND
	v_and_or_b32 v23, v92, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v22, v23, v89
	v_pk_mul_f16 v22, v22, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v22, v67, v6
	;;#ASMEND
	s_waitcnt vmcnt(11)
	v_lshrrev_b32_e32 v67, 8, v73
	v_and_or_b32 v65, v92, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v66, v65, v4
	v_pk_mul_f16 v66, v66, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v66, v68, v6
	;;#ASMEND
	v_and_or_b32 v65, v73, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v86, v65, v89
	v_pk_mul_f16 v86, v86, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v86, v69, v6
	;;#ASMEND
	v_and_or_b32 v66, v73, s13, 0x54005400
	v_lshrrev_b32_e32 v65, 8, v74
	;;#ASMSTART
	v_pk_add_f16 v69, v66, v4
	v_pk_mul_f16 v69, v69, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v69, v70, v6
	;;#ASMEND
	v_and_or_b32 v66, v67, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v69, v66, v89
	v_pk_mul_f16 v69, v69, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v69, v71, v6
	;;#ASMEND
	v_and_or_b32 v67, v67, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v69, v67, v4
	v_pk_mul_f16 v69, v69, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v69, v72, v6
	;;#ASMEND
	v_and_or_b32 v68, v74, s12, 0x64006400
	v_and_or_b32 v73, v74, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v74, v68, v89
	v_pk_mul_f16 v74, v74, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v74, v13, v6
	;;#ASMEND
	v_lshrrev_b32_e32 v69, 8, v75
	;;#ASMSTART
	v_pk_add_f16 v68, v73, v4
	v_pk_mul_f16 v68, v68, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v68, v14, v6
	;;#ASMEND
	v_and_or_b32 v73, v65, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v13, v73, v89
	v_pk_mul_f16 v13, v13, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v13, v15, v6
	;;#ASMEND
	v_and_or_b32 v65, v65, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v13, v65, v4
	v_pk_mul_f16 v13, v13, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v13, v16, v6
	;;#ASMEND
	v_and_or_b32 v66, v75, s12, 0x64006400
	v_and_or_b32 v67, v75, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v75, v66, v89
	v_pk_mul_f16 v75, v75, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v75, v17, v6
	;;#ASMEND
	v_lshrrev_b32_e32 v72, 8, v76
	;;#ASMSTART
	v_pk_add_f16 v17, v67, v4
	v_pk_mul_f16 v17, v17, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v17, v18, v6
	;;#ASMEND
	v_and_or_b32 v17, v69, s12, 0x64006400
	v_and_or_b32 v18, v69, s13, 0x54005400
	v_add_co_u32 v83, vcc_lo, v7, v88
	v_and_or_b32 v70, v76, s12, 0x64006400
	v_and_or_b32 v71, v76, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v67, v71, v4
	v_pk_mul_f16 v67, v67, v90
	;;#ASMEND
	v_add_co_ci_u32_e64 v84, null, 0, v8, vcc_lo
	v_add_co_u32 v87, vcc_lo, v9, v93
	v_and_or_b32 v69, v72, s13, 0x54005400
	v_add_co_ci_u32_e64 v88, null, 0, v10, vcc_lo
	s_waitcnt vmcnt(6)
	v_bfe_u32 v85, v85, v12, 4
	s_clause 0x1
	global_load_b128 v[21:24], v[81:82], off
	global_load_b128 v[13:16], v[81:82], off offset:16
	s_waitcnt vmcnt(4)
	v_and_or_b32 v74, v62, s12, 0x64006400
	v_and_or_b32 v68, v62, s13, 0x54005400
	v_lshrrev_b32_e32 v73, 8, v62
	;;#ASMSTART
	v_pk_add_f16 v62, v17, v89
	v_pk_mul_f16 v62, v62, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v62, v19, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v17, v18, v4
	v_pk_mul_f16 v17, v17, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v17, v20, v6
	;;#ASMEND
	v_bfe_u32 v62, v95, v12, 4
	v_and_or_b32 v65, v63, s12, 0x64006400
	v_and_or_b32 v86, v63, s13, 0x54005400
	v_lshrrev_b32_e32 v92, 8, v63
	;;#ASMSTART
	v_pk_add_f16 v63, v70, v89
	v_pk_mul_f16 v63, v63, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v63, v45, v6
	;;#ASMEND
	v_and_or_b32 v66, v61, s12, 0x64006400
	v_and_or_b32 v76, v61, s13, 0x54005400
	v_lshrrev_b32_e32 v61, 8, v61
	;;#ASMSTART
	v_dot2_f32_f16 v6, v67, v46, v6
	;;#ASMEND
	v_and_or_b32 v93, v64, s12, 0x64006400
	v_and_or_b32 v94, v64, s13, 0x54005400
	v_lshrrev_b32_e32 v96, 8, v64
	v_and_or_b32 v64, v72, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v72, v64, v89
	v_pk_mul_f16 v72, v72, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v72, v47, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v64, v69, v4
	v_pk_mul_f16 v64, v64, v90
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v64, v48, v6
	;;#ASMEND
	s_waitcnt vmcnt(3)
	v_lshl_or_b32 v70, v91, 16, v91
	v_mad_u32_u24 v71, v62, s10, 0xe400e400
	;;#ASMSTART
	v_pk_add_f16 v45, v66, v71
	v_pk_mul_f16 v45, v45, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v45, v25, v6
	;;#ASMEND
	v_mad_u32_u24 v97, v62, s11, 0xd400d400
	;;#ASMSTART
	v_pk_add_f16 v25, v76, v97
	v_pk_mul_f16 v25, v25, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v25, v26, v6
	;;#ASMEND
	v_and_or_b32 v25, v61, s12, 0x64006400
	v_and_or_b32 v26, v61, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v61, v25, v71
	v_pk_mul_f16 v61, v61, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v61, v27, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v25, v26, v97
	v_pk_mul_f16 v25, v25, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v25, v28, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v62, v74, v71
	v_pk_mul_f16 v62, v62, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v62, v29, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v63, v68, v97
	v_pk_mul_f16 v63, v63, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v63, v30, v6
	;;#ASMEND
	v_and_or_b32 v61, v73, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v64, v61, v71
	v_pk_mul_f16 v64, v64, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v64, v31, v6
	;;#ASMEND
	v_and_or_b32 v29, v73, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v30, v29, v97
	v_pk_mul_f16 v30, v30, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v30, v32, v6
	;;#ASMEND
	global_load_b128 v[29:32], v[83:84], off slc dlc
	;;#ASMSTART
	v_pk_add_f16 v66, v65, v71
	v_pk_mul_f16 v66, v66, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v66, v33, v6
	;;#ASMEND
	s_waitcnt vmcnt(3)
	v_lshrrev_b32_e32 v69, 8, v77
	;;#ASMSTART
	v_pk_add_f16 v33, v86, v97
	v_pk_mul_f16 v33, v33, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v33, v34, v6
	;;#ASMEND
	v_and_or_b32 v75, v77, s12, 0x64006400
	v_and_or_b32 v4, v77, s13, 0x54005400
	v_and_or_b32 v33, v92, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v76, v33, v71
	v_pk_mul_f16 v76, v76, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v76, v35, v6
	;;#ASMEND
	v_and_or_b32 v34, v92, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v76, v75, v71
	v_pk_mul_f16 v76, v76, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v75, v4, v97
	v_pk_mul_f16 v75, v75, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v4, v34, v97
	v_pk_mul_f16 v4, v4, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v4, v36, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v73, v93, v71
	v_pk_mul_f16 v73, v73, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v73, v37, v6
	;;#ASMEND
	v_and_or_b32 v89, v78, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v74, v94, v97
	v_pk_mul_f16 v74, v74, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v74, v38, v6
	;;#ASMEND
	v_and_or_b32 v77, v78, s12, 0x64006400
	v_lshrrev_b32_e32 v72, 8, v78
	v_and_or_b32 v78, v79, s12, 0x64006400
	v_and_or_b32 v90, v79, s13, 0x54005400
	v_lshrrev_b32_e32 v79, 8, v79
	v_and_or_b32 v91, v80, s12, 0x64006400
	v_and_or_b32 v95, v80, s13, 0x54005400
	v_lshrrev_b32_e32 v80, 8, v80
	global_load_b128 v[65:68], v[83:84], off offset:16 slc dlc
	v_and_or_b32 v33, v96, s12, 0x64006400
	v_and_or_b32 v4, v69, s12, 0x64006400
	v_and_or_b32 v34, v69, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v69, v89, v97
	v_pk_mul_f16 v69, v69, v70
	;;#ASMEND
	v_and_or_b32 v35, v96, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v36, v77, v71
	v_pk_mul_f16 v36, v36, v70
	;;#ASMEND
	v_and_or_b32 v77, v72, s12, 0x64006400
	v_and_or_b32 v72, v72, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v83, v78, v71
	v_pk_mul_f16 v83, v83, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v78, v90, v97
	v_pk_mul_f16 v78, v78, v70
	;;#ASMEND
	s_clause 0x3
	global_load_b128 v[17:20], v[81:82], off offset:32
	global_load_b128 v[45:48], v[81:82], off offset:48
	global_load_b128 v[25:28], v[81:82], off offset:64
	global_load_b128 v[61:64], v[81:82], off offset:80
	s_waitcnt vmcnt(5)
	v_and_or_b32 v84, v29, s12, 0x64006400
	v_and_or_b32 v86, v29, s13, 0x54005400
	v_lshrrev_b32_e32 v89, 8, v29
	;;#ASMSTART
	v_pk_add_f16 v29, v33, v71
	v_pk_mul_f16 v29, v29, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v29, v39, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v29, v35, v97
	v_pk_mul_f16 v29, v29, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v29, v40, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v76, v49, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v75, v50, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v29, v4, v71
	v_pk_mul_f16 v29, v29, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v29, v51, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v29, v34, v97
	v_pk_mul_f16 v29, v29, v70
	;;#ASMEND
	v_and_or_b32 v37, v30, s12, 0x64006400
	v_and_or_b32 v38, v30, s13, 0x54005400
	v_lshrrev_b32_e32 v33, 8, v30
	v_and_or_b32 v35, v31, s12, 0x64006400
	v_and_or_b32 v39, v31, s13, 0x54005400
	v_lshrrev_b32_e32 v40, 8, v31
	v_and_or_b32 v73, v32, s12, 0x64006400
	v_and_or_b32 v74, v32, s13, 0x54005400
	v_lshrrev_b32_e32 v90, 8, v32
	;;#ASMSTART
	v_dot2_f32_f16 v6, v29, v52, v6
	;;#ASMEND
	v_and_or_b32 v29, v79, s12, 0x64006400
	v_and_or_b32 v30, v79, s13, 0x54005400
	v_and_or_b32 v31, v80, s12, 0x64006400
	v_and_or_b32 v32, v80, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v75, v91, v71
	v_pk_mul_f16 v75, v75, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v76, v95, v97
	v_pk_mul_f16 v76, v76, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v79, v77, v71
	v_pk_mul_f16 v79, v79, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v77, v72, v97
	v_pk_mul_f16 v77, v77, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v72, v29, v71
	v_pk_mul_f16 v72, v72, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v80, v30, v97
	v_pk_mul_f16 v80, v80, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v91, v31, v71
	v_pk_mul_f16 v91, v91, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v71, v32, v97
	v_pk_mul_f16 v71, v71, v70
	;;#ASMEND
	global_load_b128 v[29:32], v[81:82], off offset:96
	global_load_u16 v70, v[87:88], off
	;;#ASMSTART
	v_dot2_f32_f16 v6, v36, v41, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v69, v42, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v79, v43, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v77, v44, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v83, v53, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v78, v54, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v72, v55, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v80, v56, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v75, v57, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v76, v58, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v91, v59, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v71, v60, v6
	;;#ASMEND
	v_mad_u32_u24 v87, v85, s10, 0xe400e400
	s_waitcnt vmcnt(6)
	v_and_or_b32 v93, v65, s13, 0x54005400
	v_mad_u32_u24 v85, v85, s11, 0xd400d400
	v_and_or_b32 v36, v89, s12, 0x64006400
	v_and_or_b32 v41, v89, s13, 0x54005400
	v_and_or_b32 v92, v65, s12, 0x64006400
	v_lshrrev_b32_e32 v65, 8, v65
	v_and_or_b32 v44, v90, s12, 0x64006400
	v_lshrrev_b32_e32 v4, 8, v66
	v_and_or_b32 v49, v66, s12, 0x64006400
	v_and_or_b32 v50, v66, s13, 0x54005400
	v_and_or_b32 v79, v65, s12, 0x64006400
	v_and_or_b32 v65, v65, s13, 0x54005400
	v_lshrrev_b32_e32 v52, 8, v67
	v_and_or_b32 v34, v67, s12, 0x64006400
	v_and_or_b32 v51, v67, s13, 0x54005400
	v_and_or_b32 v66, v68, s12, 0x64006400
	v_and_or_b32 v67, v68, s13, 0x54005400
	v_lshrrev_b32_e32 v68, 8, v68
	s_waitcnt vmcnt(0)
	v_lshl_or_b32 v70, v70, 16, v70
	;;#ASMSTART
	v_pk_add_f16 v88, v84, v87
	v_pk_mul_f16 v88, v88, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v88, v21, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v84, v86, v85
	v_pk_mul_f16 v84, v84, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v84, v22, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v77, v93, v85
	v_pk_mul_f16 v77, v77, v70
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v93, v36, v87
	v_pk_mul_f16 v93, v93, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v93, v23, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v94, v41, v85
	v_pk_mul_f16 v94, v94, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v94, v24, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v86, v37, v87
	v_pk_mul_f16 v86, v86, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v86, v13, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v37, v38, v85
	v_pk_mul_f16 v37, v37, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v37, v14, v6
	;;#ASMEND
	v_and_or_b32 v38, v33, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v41, v38, v87
	v_pk_mul_f16 v41, v41, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v41, v15, v6
	;;#ASMEND
	v_and_or_b32 v33, v33, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v38, v33, v85
	v_pk_mul_f16 v38, v38, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v38, v16, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v42, v35, v87
	v_pk_mul_f16 v42, v42, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v42, v17, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v69, v39, v85
	v_pk_mul_f16 v69, v69, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v69, v18, v6
	;;#ASMEND
	v_and_or_b32 v35, v40, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v95, v35, v87
	v_pk_mul_f16 v95, v95, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v95, v19, v6
	;;#ASMEND
	v_and_or_b32 v39, v40, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v96, v39, v85
	v_pk_mul_f16 v96, v96, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v96, v20, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v40, v73, v87
	v_pk_mul_f16 v40, v40, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v40, v45, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v43, v74, v85
	v_pk_mul_f16 v43, v43, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v43, v46, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v39, v44, v87
	v_pk_mul_f16 v39, v39, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v39, v47, v6
	;;#ASMEND
	v_and_or_b32 v73, v90, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v44, v73, v85
	v_pk_mul_f16 v44, v44, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v44, v48, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v74, v92, v87
	v_pk_mul_f16 v74, v74, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v74, v25, v6
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v77, v26, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v73, v79, v87
	v_pk_mul_f16 v73, v73, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v73, v27, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v79, v65, v85
	v_pk_mul_f16 v79, v79, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v79, v28, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v89, v49, v87
	v_pk_mul_f16 v89, v89, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v89, v61, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v49, v50, v85
	v_pk_mul_f16 v49, v49, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v49, v62, v6
	;;#ASMEND
	v_and_or_b32 v50, v4, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v65, v50, v87
	v_pk_mul_f16 v65, v65, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v65, v63, v6
	;;#ASMEND
	v_and_or_b32 v4, v4, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v50, v4, v85
	v_pk_mul_f16 v50, v50, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v50, v64, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v90, v34, v87
	v_pk_mul_f16 v90, v90, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v90, v29, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v92, v51, v85
	v_pk_mul_f16 v92, v92, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v92, v30, v6
	;;#ASMEND
	v_and_or_b32 v34, v52, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v4, v34, v87
	v_pk_mul_f16 v4, v4, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v4, v31, v6
	;;#ASMEND
	v_and_or_b32 v51, v52, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v97, v51, v85
	v_pk_mul_f16 v97, v97, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v97, v32, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v52, v66, v87
	v_pk_mul_f16 v52, v52, v70
	;;#ASMEND
	global_load_b128 v[33:36], v[81:82], off offset:112
	s_waitcnt vmcnt(0)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v52, v33, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v66, v67, v85
	v_pk_mul_f16 v66, v66, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v66, v34, v6
	;;#ASMEND
	v_and_or_b32 v67, v68, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v51, v67, v87
	v_pk_mul_f16 v51, v51, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v51, v35, v6
	;;#ASMEND
	v_and_or_b32 v68, v68, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v67, v68, v85
	v_pk_mul_f16 v67, v67, v70
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v67, v36, v6
	;;#ASMEND
	s_cbranch_scc0 .LBB0_15
; %bb.16:
	s_cmp_lg_u32 s4, 0
	s_cselect_b32 s5, -1, 0
	s_delay_alu instid0(SALU_CYCLE_1)
	s_and_b32 vcc_lo, exec_lo, s5
	s_cbranch_vccz .LBB0_18
	s_branch .LBB0_24
.LBB0_17:
	v_mov_b32_e32 v6, 0
.LBB0_18:
	v_mbcnt_lo_u32_b32 v2, -1, 0
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_2)
	v_bfi_b32 v3, v2, 0, 32
	v_xor_b32_e32 v4, 16, v2
	v_xor_b32_e32 v5, 8, v2
	v_cmp_lt_u32_e32 vcc_lo, v4, v3
	v_cndmask_b32_e32 v4, v2, v4, vcc_lo
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_cmp_lt_u32_e32 vcc_lo, v5, v3
	v_cndmask_b32_e32 v5, v2, v5, vcc_lo
	v_lshlrev_b32_e32 v5, 2, v5
	s_delay_alu instid0(VALU_DEP_4)
	v_lshlrev_b32_e32 v4, 2, v4
	ds_bpermute_b32 v4, v4, v6
	s_waitcnt lgkmcnt(0)
	v_add_f32_e32 v4, v6, v4
	v_xor_b32_e32 v6, 4, v2
	ds_bpermute_b32 v5, v5, v4
	v_cmp_lt_u32_e32 vcc_lo, v6, v3
	v_cndmask_b32_e32 v6, v2, v6, vcc_lo
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_1)
	v_lshlrev_b32_e32 v6, 2, v6
	s_waitcnt lgkmcnt(0)
	v_add_f32_e32 v4, v4, v5
	ds_bpermute_b32 v5, v6, v4
	v_xor_b32_e32 v6, 2, v2
	v_cmp_lt_u32_e32 vcc_lo, v6, v3
	v_cndmask_b32_e32 v6, v2, v6, vcc_lo
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_1)
	v_lshlrev_b32_e32 v6, 2, v6
	s_waitcnt lgkmcnt(0)
	v_add_f32_e32 v4, v4, v5
	ds_bpermute_b32 v5, v6, v4
	v_xor_b32_e32 v6, 1, v2
	v_cmp_lt_u32_e32 vcc_lo, v6, v3
	v_cndmask_b32_e32 v3, v2, v6, vcc_lo
	v_cmp_eq_u32_e32 vcc_lo, 0, v0
	s_waitcnt lgkmcnt(0)
	s_delay_alu instid0(VALU_DEP_2)
	v_dual_add_f32 v2, v4, v5 :: v_dual_lshlrev_b32 v3, 2, v3
	ds_bpermute_b32 v3, v3, v2
	s_and_b32 exec_lo, exec_lo, vcc_lo
	s_cbranch_execz .LBB0_22
; %bb.19:
	s_load_b128 s[0:3], s[0:1], 0x48
	s_waitcnt lgkmcnt(0)
	v_add_f32_e32 v0, v2, v3
	v_mov_b32_e32 v2, 0
	s_cmp_eq_f32 s9, 0
	s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
	v_mul_f32_e32 v3, s8, v0
	v_lshlrev_b64 v[0:1], 1, v[1:2]
	s_cbranch_scc1 .LBB0_21
; %bb.20:
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_add_co_u32 v4, vcc_lo, s2, v0
	v_add_co_ci_u32_e64 v5, null, s3, v1, vcc_lo
	global_load_d16_b16 v2, v[4:5], off
	s_waitcnt vmcnt(0)
	v_fma_mix_f32 v3, s9, v2, v3 op_sel_hi:[0,1,0]
.LBB0_21:
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
	v_add_co_u32 v0, vcc_lo, s0, v0
	v_cvt_f16_f32_e32 v2.l, v3
	s_delay_alu instid0(VALU_DEP_3)
	v_add_co_ci_u32_e64 v1, null, s1, v1, vcc_lo
	global_store_b16 v[0:1], v2, off
.LBB0_22:
	s_nop 0
	s_sendmsg sendmsg(MSG_DEALLOC_VGPRS)
	s_endpgm
.LBB0_23:
	v_mov_b32_e32 v6, 0
	s_cbranch_execz .LBB0_18
.LBB0_24:
	v_mov_b32_e32 v5, 0
	s_mov_b32 s5, 0
	s_mov_b32 s10, 0x10001
	s_mov_b32 s11, 0x100010
	s_mov_b32 s12, 0xf000f
	s_mov_b32 s13, 0xf000f0
.LBB0_25:                               ; =>This Inner Loop Header: Depth=1
	v_lshl_add_u32 v4, s2, 11, v11
	s_add_i32 s5, s5, 1
	s_add_i32 s2, s2, 1
	s_cmp_eq_u32 s5, s4
	s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
	v_subrev_nc_u32_e32 v13, s3, v4
	v_min_u32_e32 v4, v4, v13
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
	v_lshrrev_b32_e32 v15, 1, v4
	v_lshrrev_b32_e32 v16, 7, v4
	v_lshlrev_b64 v[13:14], 1, v[4:5]
	v_and_b32_e32 v4, 0x7ffffffc, v15
	s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_1)
	v_add_co_u32 v15, vcc_lo, v2, v16
	v_lshlrev_b32_e32 v17, 1, v16
	v_add_co_ci_u32_e64 v16, null, 0, v3, vcc_lo
	v_add_co_u32 v49, vcc_lo, s6, v13
	v_add_co_ci_u32_e64 v50, null, s7, v14, vcc_lo
	global_load_u8 v53, v[15:16], off
	v_add_co_u32 v13, vcc_lo, v9, v17
	s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
	v_add_co_ci_u32_e64 v14, null, 0, v10, vcc_lo
	v_add_co_u32 v17, vcc_lo, v7, v4
	v_add_co_ci_u32_e64 v18, null, 0, v8, vcc_lo
	global_load_u16 v4, v[13:14], off
	s_clause 0x1
	global_load_b128 v[13:16], v[17:18], off slc dlc
	global_load_b128 v[17:20], v[17:18], off offset:16 slc dlc
	s_clause 0x7
	global_load_b128 v[21:24], v[49:50], off
	global_load_b128 v[25:28], v[49:50], off offset:16
	global_load_b128 v[29:32], v[49:50], off offset:32
	global_load_b128 v[33:36], v[49:50], off offset:48
	global_load_b128 v[37:40], v[49:50], off offset:64
	global_load_b128 v[41:44], v[49:50], off offset:80
	global_load_b128 v[45:48], v[49:50], off offset:96
	global_load_b128 v[49:52], v[49:50], off offset:112
	s_waitcnt vmcnt(11)
	v_bfe_u32 v53, v53, v12, 4
	s_waitcnt vmcnt(10)
	v_lshl_or_b32 v4, v4, 16, v4
	s_waitcnt vmcnt(9)
	v_and_or_b32 v55, v13, s12, 0x64006400
	v_and_or_b32 v56, v13, s13, 0x54005400
	v_lshrrev_b32_e32 v13, 8, v13
	v_mad_u32_u24 v54, v53, s10, 0xe400e400
	;;#ASMSTART
	v_pk_add_f16 v71, v55, v54
	v_pk_mul_f16 v71, v71, v4
	;;#ASMEND
	s_waitcnt vmcnt(7)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v71, v21, v6
	;;#ASMEND
	v_mad_u32_u24 v53, v53, s11, 0xd400d400
	v_and_or_b32 v57, v14, s12, 0x64006400
	v_and_or_b32 v58, v14, s13, 0x54005400
	v_lshrrev_b32_e32 v14, 8, v14
	;;#ASMSTART
	v_pk_add_f16 v55, v56, v53
	v_pk_mul_f16 v55, v55, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v55, v22, v6
	;;#ASMEND
	v_and_or_b32 v56, v13, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v21, v56, v54
	v_pk_mul_f16 v21, v21, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v21, v23, v6
	;;#ASMEND
	v_and_or_b32 v13, v13, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v22, v13, v53
	v_pk_mul_f16 v22, v22, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v22, v24, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v72, v57, v54
	v_pk_mul_f16 v72, v72, v4
	;;#ASMEND
	s_waitcnt vmcnt(6)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v72, v25, v6
	;;#ASMEND
	v_and_or_b32 v59, v15, s12, 0x64006400
	v_and_or_b32 v60, v15, s13, 0x54005400
	v_lshrrev_b32_e32 v15, 8, v15
	;;#ASMSTART
	v_pk_add_f16 v57, v58, v53
	v_pk_mul_f16 v57, v57, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v57, v26, v6
	;;#ASMEND
	v_and_or_b32 v58, v14, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v13, v58, v54
	v_pk_mul_f16 v13, v13, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v13, v27, v6
	;;#ASMEND
	v_and_or_b32 v14, v14, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v55, v14, v53
	v_pk_mul_f16 v55, v55, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v55, v28, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v73, v59, v54
	v_pk_mul_f16 v73, v73, v4
	;;#ASMEND
	s_waitcnt vmcnt(5)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v73, v29, v6
	;;#ASMEND
	v_and_or_b32 v61, v16, s12, 0x64006400
	v_and_or_b32 v62, v16, s13, 0x54005400
	v_lshrrev_b32_e32 v16, 8, v16
	;;#ASMSTART
	v_pk_add_f16 v59, v60, v53
	v_pk_mul_f16 v59, v59, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v59, v30, v6
	;;#ASMEND
	v_and_or_b32 v60, v15, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v14, v60, v54
	v_pk_mul_f16 v14, v14, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v14, v31, v6
	;;#ASMEND
	v_and_or_b32 v15, v15, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v56, v15, v53
	v_pk_mul_f16 v56, v56, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v56, v32, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v74, v61, v54
	v_pk_mul_f16 v74, v74, v4
	;;#ASMEND
	s_waitcnt vmcnt(4)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v74, v33, v6
	;;#ASMEND
	v_and_or_b32 v63, v17, s12, 0x64006400
	v_and_or_b32 v64, v17, s13, 0x54005400
	v_lshrrev_b32_e32 v17, 8, v17
	;;#ASMSTART
	v_pk_add_f16 v61, v62, v53
	v_pk_mul_f16 v61, v61, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v61, v34, v6
	;;#ASMEND
	v_and_or_b32 v62, v16, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v15, v62, v54
	v_pk_mul_f16 v15, v15, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v15, v35, v6
	;;#ASMEND
	v_and_or_b32 v16, v16, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v58, v16, v53
	v_pk_mul_f16 v58, v58, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v58, v36, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v75, v63, v54
	v_pk_mul_f16 v75, v75, v4
	;;#ASMEND
	s_waitcnt vmcnt(3)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v75, v37, v6
	;;#ASMEND
	v_and_or_b32 v65, v18, s12, 0x64006400
	v_and_or_b32 v66, v18, s13, 0x54005400
	v_lshrrev_b32_e32 v18, 8, v18
	;;#ASMSTART
	v_pk_add_f16 v63, v64, v53
	v_pk_mul_f16 v63, v63, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v63, v38, v6
	;;#ASMEND
	v_and_or_b32 v64, v17, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v16, v64, v54
	v_pk_mul_f16 v16, v16, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v16, v39, v6
	;;#ASMEND
	v_and_or_b32 v17, v17, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v60, v17, v53
	v_pk_mul_f16 v60, v60, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v60, v40, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v76, v65, v54
	v_pk_mul_f16 v76, v76, v4
	;;#ASMEND
	s_waitcnt vmcnt(2)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v76, v41, v6
	;;#ASMEND
	v_and_or_b32 v67, v19, s12, 0x64006400
	v_and_or_b32 v68, v19, s13, 0x54005400
	v_lshrrev_b32_e32 v19, 8, v19
	;;#ASMSTART
	v_pk_add_f16 v65, v66, v53
	v_pk_mul_f16 v65, v65, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v65, v42, v6
	;;#ASMEND
	v_and_or_b32 v66, v18, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v17, v66, v54
	v_pk_mul_f16 v17, v17, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v17, v43, v6
	;;#ASMEND
	v_and_or_b32 v18, v18, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v62, v18, v53
	v_pk_mul_f16 v62, v62, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v62, v44, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v77, v67, v54
	v_pk_mul_f16 v77, v77, v4
	;;#ASMEND
	s_waitcnt vmcnt(1)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v77, v45, v6
	;;#ASMEND
	v_and_or_b32 v69, v20, s12, 0x64006400
	v_and_or_b32 v70, v20, s13, 0x54005400
	v_lshrrev_b32_e32 v20, 8, v20
	;;#ASMSTART
	v_pk_add_f16 v67, v68, v53
	v_pk_mul_f16 v67, v67, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v67, v46, v6
	;;#ASMEND
	v_and_or_b32 v68, v19, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v18, v68, v54
	v_pk_mul_f16 v18, v18, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v18, v47, v6
	;;#ASMEND
	v_and_or_b32 v19, v19, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v64, v19, v53
	v_pk_mul_f16 v64, v64, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v64, v48, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v78, v69, v54
	v_pk_mul_f16 v78, v78, v4
	;;#ASMEND
	s_waitcnt vmcnt(0)
	;;#ASMSTART
	v_dot2_f32_f16 v6, v78, v49, v6
	;;#ASMEND
	;;#ASMSTART
	v_pk_add_f16 v69, v70, v53
	v_pk_mul_f16 v69, v69, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v69, v50, v6
	;;#ASMEND
	v_and_or_b32 v70, v20, s12, 0x64006400
	;;#ASMSTART
	v_pk_add_f16 v19, v70, v54
	v_pk_mul_f16 v19, v19, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v19, v51, v6
	;;#ASMEND
	v_and_or_b32 v20, v20, s13, 0x54005400
	;;#ASMSTART
	v_pk_add_f16 v54, v20, v53
	v_pk_mul_f16 v54, v54, v4
	;;#ASMEND
	;;#ASMSTART
	v_dot2_f32_f16 v6, v54, v52, v6
	;;#ASMEND
	s_cbranch_scc0 .LBB0_25
	s_branch .LBB0_18
.Lfunc_end0:
	.size	Custom_W4A16_Decode_G128_ExLlama_gfx1151, .Lfunc_end0-Custom_W4A16_Decode_G128_ExLlama_gfx1151
	.cfi_endproc
	.section	.rodata,"a",@progbits
	.p2align	6, 0x0
	.amdhsa_kernel Custom_W4A16_Decode_G128_ExLlama_gfx1151
		.amdhsa_group_segment_fixed_size 0
		.amdhsa_private_segment_fixed_size 0
		.amdhsa_kernarg_size 160
		.amdhsa_user_sgpr_count 2
		.amdhsa_user_sgpr_dispatch_ptr 0
		.amdhsa_user_sgpr_queue_ptr 0
		.amdhsa_user_sgpr_kernarg_segment_ptr 1
		.amdhsa_user_sgpr_dispatch_id 0
		.amdhsa_user_sgpr_private_segment_size 0
		.amdhsa_wavefront_size32 1
		.amdhsa_enable_private_segment 0
		.amdhsa_system_sgpr_workgroup_id_x 1
		.amdhsa_system_sgpr_workgroup_id_y 0
		.amdhsa_system_sgpr_workgroup_id_z 0
		.amdhsa_system_sgpr_workgroup_info 0
		.amdhsa_system_vgpr_workitem_id 0
		.amdhsa_next_free_vgpr 98
		.amdhsa_next_free_sgpr 22
		.amdhsa_reserve_vcc 1
		.amdhsa_float_round_mode_32 0
		.amdhsa_float_round_mode_16_64 0
		.amdhsa_float_denorm_mode_32 3
		.amdhsa_float_denorm_mode_16_64 3
		.amdhsa_dx10_clamp 1
		.amdhsa_ieee_mode 1
		.amdhsa_fp16_overflow 0
		.amdhsa_workgroup_processor_mode 1
		.amdhsa_memory_ordered 1
		.amdhsa_forward_progress 1
		.amdhsa_shared_vgpr_count 0
		.amdhsa_inst_pref_size ((instprefsize(.Lfunc_end0-Custom_W4A16_Decode_G128_ExLlama_gfx1151)<<4)&1008)>>4
		.amdhsa_exception_fp_ieee_invalid_op 0
		.amdhsa_exception_fp_denorm_src 0
		.amdhsa_exception_fp_ieee_div_zero 0
		.amdhsa_exception_fp_ieee_overflow 0
		.amdhsa_exception_fp_ieee_underflow 0
		.amdhsa_exception_fp_ieee_inexact 0
		.amdhsa_exception_int_div_zero 0
	.end_amdhsa_kernel
	.text
                                        ; -- End function
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.num_vgpr, 98
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.num_agpr, 0
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.numbered_sgpr, 22
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.num_named_barrier, 0
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.private_seg_size, 0
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.uses_vcc, 1
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.uses_flat_scratch, 0
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.has_dyn_sized_stack, 0
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.has_recursion, 0
	.set .LCustom_W4A16_Decode_G128_ExLlama_gfx1151.has_indirect_call, 0
	.section	.AMDGPU.csdata,"",@progbits
; Kernel info:
; codeLenInByte = 16916
; TotalNumSgprs: 24
; NumVgprs: 98
; ScratchSize: 0
; MemoryBound: 0
; FloatMode: 240
; IeeeMode: 1
; LDSByteSize: 0 bytes/workgroup (compile time only)
; SGPRBlocks: 0
; VGPRBlocks: 12
; NumSGPRsForWavesPerEU: 24
; NumVGPRsForWavesPerEU: 98
; Occupancy: 12
; WaveLimiterHint : 0
; COMPUTE_PGM_RSRC2:SCRATCH_EN: 0
; COMPUTE_PGM_RSRC2:USER_SGPR: 2
; COMPUTE_PGM_RSRC2:TRAP_HANDLER: 0
; COMPUTE_PGM_RSRC2:TGID_X_EN: 1
; COMPUTE_PGM_RSRC2:TGID_Y_EN: 0
; COMPUTE_PGM_RSRC2:TGID_Z_EN: 0
; COMPUTE_PGM_RSRC2:TIDIG_COMP_CNT: 0
	.text
	.p2alignl 7, 3214868480
	.fill 96, 4, 3214868480
	.section	.AMDGPU.gpr_maximums,"",@progbits
	.set amdgpu.max_num_vgpr, 0
	.set amdgpu.max_num_agpr, 0
	.set amdgpu.max_num_sgpr, 0
	.set amdgpu.max_num_named_barrier, 0
	.text
	.type	__hip_cuid_Custom_W4A16_Decode_G128_ExLlama_gfx1151,@object             ; @__hip_cuid_Custom_W4A16_Decode_G128_ExLlama_gfx1151
	.section	.bss,"aw",@nobits
	.globl	__hip_cuid_Custom_W4A16_Decode_G128_ExLlama_gfx1151
__hip_cuid_Custom_W4A16_Decode_G128_ExLlama_gfx1151:
	.byte	0                               ; 0x0
	.size	__hip_cuid_Custom_W4A16_Decode_G128_ExLlama_gfx1151, 1

	.ident	"AMD clang version 23.0.0git (https://github.com/ROCm/llvm-project.git 0bace1908348b840e6aa1b4b6e12151dae208158)"
	.section	".note.GNU-stack","",@progbits
	.addrsig
	.addrsig_sym __hip_cuid_Custom_W4A16_Decode_G128_ExLlama_gfx1151
	.amdgpu_metadata
---
custom.config:
  InternalSupportParams:
    KernArgsVersion: 3
    UseUniversalArgs: true
    SupportUserGSU: false
    SupportCustomWGM: false
    SupportCustomStaggerU: false
  WorkGroup:
  - 4
  - 1
  - 32
  ThreadTile:
  - 1
  - 1
  WavefrontSize: 32
  WaveSplitK: true
  DepthU: 256
  GlobalReadVectorWidthA: 8
  GlobalReadVectorWidthB: 1
  VectorWidthA: 1
  VectorWidthB: 1
  LocalReadVectorWidth: 2
  StoreVectorWidth: 1
  PrefetchGlobalRead: 1
  PrefetchLocalRead: 0
  ScheduleIterAlg: 0
  TransposeLDS: 2
  StaggerU: 0
  GlobalSplitU: 1
  WorkGroupMapping: 1
  AssertSummationElementMultiple: 256
  AssertSizeEqual:
    1: 1
    2: 1
  AssertSizeGreaterThan:
    3: 0
amdhsa.kernels:
  - .args:
      - .offset:         0
        .size:           4
        .value_kind:     by_value
      - .offset:         4
        .size:           4
        .value_kind:     by_value
      - .offset:         8
        .size:           4
        .value_kind:     by_value
      - .offset:         12
        .size:           4
        .value_kind:     by_value
      - .offset:         16
        .size:           4
        .value_kind:     by_value
      - .offset:         20
        .size:           4
        .value_kind:     by_value
      - .offset:         24
        .size:           4
        .value_kind:     by_value
      - .offset:         28
        .size:           4
        .value_kind:     by_value
      - .actual_access:  read_only
        .address_space:  global
        .offset:         32
        .size:           8
        .value_kind:     global_buffer
      - .actual_access:  read_only
        .address_space:  global
        .offset:         40
        .size:           8
        .value_kind:     global_buffer
      - .offset:         48
        .size:           4
        .value_kind:     by_value
      - .offset:         52
        .size:           4
        .value_kind:     by_value
      - .offset:         56
        .size:           4
        .value_kind:     by_value
      - .offset:         60
        .size:           4
        .value_kind:     by_value
      - .offset:         64
        .size:           4
        .value_kind:     by_value
      - .offset:         68
        .size:           4
        .value_kind:     by_value
      - .address_space:  global
        .offset:         72
        .size:           8
        .value_kind:     global_buffer
      - .address_space:  global
        .offset:         80
        .size:           8
        .value_kind:     global_buffer
      - .offset:         88
        .size:           4
        .value_kind:     by_value
      - .offset:         92
        .size:           4
        .value_kind:     by_value
      - .offset:         96
        .size:           4
        .value_kind:     by_value
      - .offset:         100
        .size:           4
        .value_kind:     by_value
      - .actual_access:  read_only
        .address_space:  global
        .offset:         104
        .size:           8
        .value_kind:     global_buffer
      - .address_space:  global
        .offset:         112
        .size:           8
        .value_kind:     global_buffer
      - .actual_access:  read_only
        .address_space:  global
        .offset:         120
        .size:           8
        .value_kind:     global_buffer
      - .offset:         128
        .size:           8
        .value_kind:     by_value
      - .offset:         136
        .size:           8
        .value_kind:     by_value
      - .offset:         144
        .size:           8
        .value_kind:     by_value
      - .offset:         152
        .size:           8
        .value_kind:     by_value
    .group_segment_fixed_size: 0
    .kernarg_segment_align: 8
    .kernarg_segment_size: 160
    .language:       OpenCL C
    .language_version:
      - 2
      - 0
    .max_flat_workgroup_size: 128
    .name:           Custom_W4A16_Decode_G128_ExLlama_gfx1151
    .private_segment_fixed_size: 0
    .sgpr_count:     24
    .sgpr_spill_count: 0
    .symbol:         Custom_W4A16_Decode_G128_ExLlama_gfx1151.kd
    .vgpr_count:     98
    .vgpr_spill_count: 0
    .wavefront_size: 32
amdhsa.target:   amdgcn-amd-amdhsa-unknown-gfx1151
amdhsa.version:
  - 1
  - 1
...

	.end_amdgpu_metadata
