#pragma once

// Default macros that can be used to compile the HIP kernels standalone
// on the command-line without going through their respective plans.

// provider-wide options
#ifndef HIP_PLUGIN_LAYOUT_NHWC
#define HIP_PLUGIN_LAYOUT_NHWC 0
#endif

#ifndef HIP_PLUGIN_USE_AMDGCN
#define HIP_PLUGIN_USE_AMDGCN 0
#endif

#ifndef HIP_PLUGIN_USE_FP16
#define HIP_PLUGIN_USE_FP16 0
#endif

#ifndef HIP_PLUGIN_USE_FP32
#define HIP_PLUGIN_USE_FP32 1
#endif

#ifndef HIP_PLUGIN_USE_FPMIX
#define HIP_PLUGIN_USE_FPMIX 0
#endif

#ifndef HIP_PLUGIN_USE_BFPMIX
#define HIP_PLUGIN_USE_BFPMIX 0
#endif

#ifndef HIP_PLUGIN_GFX103X
#define HIP_PLUGIN_GFX103X 0
#endif

#ifndef HIP_PLUGIN_GFX110X
#define HIP_PLUGIN_GFX110X 0
#endif

#ifndef HIP_PLUGIN_GFX115X
#define HIP_PLUGIN_GFX115X 0
#endif

#ifndef HIP_PLUGIN_GFX120X
#define HIP_PLUGIN_GFX120X 0
#endif

// batchnorm - both stats paths are enabled so the code they guard is analysed rather than
// preprocessed away.

#ifndef HIP_PLUGIN_BN_INPUT_TYPE
#define HIP_PLUGIN_BN_INPUT_TYPE float
#endif

#ifndef HIP_PLUGIN_BN_OUTPUT_TYPE
#define HIP_PLUGIN_BN_OUTPUT_TYPE float
#endif

#ifndef HIP_PLUGIN_BN_SCALE_TYPE
#define HIP_PLUGIN_BN_SCALE_TYPE float
#endif

#ifndef HIP_PLUGIN_BN_MEAN_VAR_TYPE
#define HIP_PLUGIN_BN_MEAN_VAR_TYPE float
#endif

#ifndef HIP_PLUGIN_BN_NRN_OP_ID
#define HIP_PLUGIN_BN_NRN_OP_ID 3
#endif

#ifndef HIP_PLUGIN_BN_SAVE_MEAN_VARIANCE
#define HIP_PLUGIN_BN_SAVE_MEAN_VARIANCE 1
#endif

#ifndef HIP_PLUGIN_BN_RUNNING_RESULT
#define HIP_PLUGIN_BN_RUNNING_RESULT 1
#endif

#ifndef HIP_PLUGIN_BN_USESAVED
#define HIP_PLUGIN_BN_USESAVED 1
#endif

#ifndef HIP_PLUGIN_BN_NODPP
#define HIP_PLUGIN_BN_NODPP 0
#endif

#ifndef HIP_PLUGIN_BN_VARIANT
#define HIP_PLUGIN_BN_VARIANT 1
#endif

#ifndef HIP_PLUGIN_BN_STASH_METHOD
#define HIP_PLUGIN_BN_STASH_METHOD 0
#endif

#ifndef HIP_PLUGIN_BN_VEC_SIZE
#define HIP_PLUGIN_BN_VEC_SIZE 1
#endif

#ifndef HIP_PLUGIN_BN_GRP0
#define HIP_PLUGIN_BN_GRP0 1
#endif

#ifndef HIP_PLUGIN_BN_GRP1
#define HIP_PLUGIN_BN_GRP1 1024
#endif

#ifndef HIP_PLUGIN_BN_GRP2
#define HIP_PLUGIN_BN_GRP2 1
#endif

#ifndef HIP_PLUGIN_BN_GRP0_FINAL
#define HIP_PLUGIN_BN_GRP0_FINAL 1
#endif

#ifndef HIP_PLUGIN_BN_GRP1_FINAL
#define HIP_PLUGIN_BN_GRP1_FINAL 1024
#endif

#ifndef HIP_PLUGIN_BN_GRP2_FINAL
#define HIP_PLUGIN_BN_GRP2_FINAL 1
#endif

#ifndef HIP_PLUGIN_BN_NGRPS
#define HIP_PLUGIN_BN_NGRPS 1
#endif

#ifndef HIP_PLUGIN_BN_NGRPS2
#define HIP_PLUGIN_BN_NGRPS2 1
#endif

#ifndef HIP_PLUGIN_BN_LDS_SIZE
#define HIP_PLUGIN_BN_LDS_SIZE 256
#endif

#ifndef HIP_PLUGIN_BN_LDSGCN_SIZE
#define HIP_PLUGIN_BN_LDSGCN_SIZE 16
#endif

#ifndef HIP_PLUGIN_BN_LOOP_UNROLL_MAXN
#define HIP_PLUGIN_BN_LOOP_UNROLL_MAXN 768
#endif

#ifndef HIP_PLUGIN_BN_LOOP_UNROLL_MAXHW
#define HIP_PLUGIN_BN_LOOP_UNROLL_MAXHW 2500
#endif

#ifndef HIP_PLUGIN_BN_N
#define HIP_PLUGIN_BN_N 1
#endif

#ifndef HIP_PLUGIN_BN_C
#define HIP_PLUGIN_BN_C 1
#endif

#ifndef HIP_PLUGIN_BN_HW
#define HIP_PLUGIN_BN_HW 1
#endif

#ifndef HIP_PLUGIN_BN_NHW
#define HIP_PLUGIN_BN_NHW 1
#endif

#ifndef HIP_PLUGIN_BN_CHW
#define HIP_PLUGIN_BN_CHW 1
#endif

#ifndef HIP_PLUGIN_BN_NCHW
#define HIP_PLUGIN_BN_NCHW 1
#endif

#ifndef HIP_PLUGIN_BN_N_ELEMENTS
#define HIP_PLUGIN_BN_N_ELEMENTS HIP_PLUGIN_BN_N
#endif

// RMSnorm

#ifndef HIP_PLUGIN_RMSNORM_INPUT_TYPE
#define HIP_PLUGIN_RMSNORM_INPUT_TYPE float
#endif

#ifndef HIP_PLUGIN_RMSNORM_OUTPUT_TYPE
#define HIP_PLUGIN_RMSNORM_OUTPUT_TYPE float
#endif

#ifndef HIP_PLUGIN_RMSNORM_SCALE_TYPE
#define HIP_PLUGIN_RMSNORM_SCALE_TYPE float
#endif

#ifndef HIP_PLUGIN_RMSNORM_COMPUTE_TYPE
#define HIP_PLUGIN_RMSNORM_COMPUTE_TYPE float
#endif

#ifndef HIP_PLUGIN_RMSNORM_X_TYPE
#define HIP_PLUGIN_RMSNORM_X_TYPE float
#endif

#ifndef HIP_PLUGIN_RMSNORM_Y_TYPE
#define HIP_PLUGIN_RMSNORM_Y_TYPE float
#endif

#ifndef HIP_PLUGIN_RMSNORM_DX_TYPE
#define HIP_PLUGIN_RMSNORM_DX_TYPE float
#endif

#ifndef HIP_PLUGIN_RMSNORM_DY_TYPE
#define HIP_PLUGIN_RMSNORM_DY_TYPE float
#endif

#ifndef HIP_PLUGIN_RMSNORM_NRN_OP_ID
#define HIP_PLUGIN_RMSNORM_NRN_OP_ID 0
#endif

#ifndef HIP_PLUGIN_RMSNORM_LOCAL_SIZE
#define HIP_PLUGIN_RMSNORM_LOCAL_SIZE 256
#endif

#ifndef HIP_PLUGIN_RMSNORM_INNER_SIZE
#define HIP_PLUGIN_RMSNORM_INNER_SIZE 512
#endif

#ifndef HIP_PLUGIN_RMSNORM_OUTER_SIZE
#define HIP_PLUGIN_RMSNORM_OUTER_SIZE 1
#endif

#ifndef HIP_PLUGIN_RMSNORM_STRIDE
#define HIP_PLUGIN_RMSNORM_STRIDE 1
#endif

// layernorm (plans/layernorm)
#ifndef HIP_PLUGIN_LAYERNORM_INPUT_TYPE
#define HIP_PLUGIN_LAYERNORM_INPUT_TYPE float
#endif

#ifndef HIP_PLUGIN_LAYERNORM_OUTPUT_TYPE
#define HIP_PLUGIN_LAYERNORM_OUTPUT_TYPE float
#endif

#ifndef HIP_PLUGIN_LAYERNORM_SCALE_BIAS_TYPE
#define HIP_PLUGIN_LAYERNORM_SCALE_BIAS_TYPE float
#endif

#ifndef HIP_PLUGIN_LAYERNORM_MEAN_INV_VARIANCE_TYPE
#define HIP_PLUGIN_LAYERNORM_MEAN_INV_VARIANCE_TYPE float
#endif

#ifndef HIP_PLUGIN_LAYERNORM_LOCAL_SIZE
#define HIP_PLUGIN_LAYERNORM_LOCAL_SIZE 256
#endif

#ifndef HIP_PLUGIN_LAYERNORM_INNER_SIZE
#define HIP_PLUGIN_LAYERNORM_INNER_SIZE 256
#endif

#ifndef HIP_PLUGIN_LAYERNORM_OUTER_SIZE
#define HIP_PLUGIN_LAYERNORM_OUTER_SIZE 1
#endif

#ifndef HIP_PLUGIN_LAYERNORM_STRIDE
#define HIP_PLUGIN_LAYERNORM_STRIDE 1
#endif

#ifndef HIP_PLUGIN_LAYERNORM_PARALLEL_SIZE
#define HIP_PLUGIN_LAYERNORM_PARALLEL_SIZE 1
#endif

// resample - a 2D 8x8 -> 4x4 pooling with a 2x2 window and packed NCHW strides.
#ifndef HIP_PLUGIN_RESAMPLE_INPUT_TYPE
#define HIP_PLUGIN_RESAMPLE_INPUT_TYPE float
#endif

#ifndef HIP_PLUGIN_RESAMPLE_OUTPUT_TYPE
#define HIP_PLUGIN_RESAMPLE_OUTPUT_TYPE float
#endif

#ifndef HIP_PLUGIN_RESAMPLE_COMPUTE_TYPE
#define HIP_PLUGIN_RESAMPLE_COMPUTE_TYPE float
#endif

#ifndef HIP_PLUGIN_RESAMPLE_INDEX_TYPE
#define HIP_PLUGIN_RESAMPLE_INDEX_TYPE int
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_TYPE
#define HIP_PLUGIN_RESAMPLE_DX_TYPE float
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_TYPE
#define HIP_PLUGIN_RESAMPLE_DY_TYPE float
#endif

#ifndef HIP_PLUGIN_RESAMPLE_MODE
#define HIP_PLUGIN_RESAMPLE_MODE 0
#endif

#ifndef HIP_PLUGIN_RESAMPLE_PADDING_MODE
#define HIP_PLUGIN_RESAMPLE_PADDING_MODE 0
#endif

#ifndef HIP_PLUGIN_RESAMPLE_SPATIAL_DIMS
#define HIP_PLUGIN_RESAMPLE_SPATIAL_DIMS 2
#endif

#ifndef HIP_PLUGIN_RESAMPLE_HAS_INDEX
#define HIP_PLUGIN_RESAMPLE_HAS_INDEX 0
#endif

#ifndef HIP_PLUGIN_RESAMPLE_GENERATE_INDEX
#define HIP_PLUGIN_RESAMPLE_GENERATE_INDEX 0
#endif

#ifndef HIP_PLUGIN_RESAMPLE_N
#define HIP_PLUGIN_RESAMPLE_N 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_C
#define HIP_PLUGIN_RESAMPLE_C 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_X_D
#define HIP_PLUGIN_RESAMPLE_X_D 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_X_H
#define HIP_PLUGIN_RESAMPLE_X_H 8
#endif

#ifndef HIP_PLUGIN_RESAMPLE_X_W
#define HIP_PLUGIN_RESAMPLE_X_W 8
#endif

#ifndef HIP_PLUGIN_RESAMPLE_Y_D
#define HIP_PLUGIN_RESAMPLE_Y_D 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_Y_H
#define HIP_PLUGIN_RESAMPLE_Y_H 4
#endif

#ifndef HIP_PLUGIN_RESAMPLE_Y_W
#define HIP_PLUGIN_RESAMPLE_Y_W 4
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_D
#define HIP_PLUGIN_RESAMPLE_DX_D 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_H
#define HIP_PLUGIN_RESAMPLE_DX_H 8
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_W
#define HIP_PLUGIN_RESAMPLE_DX_W 8
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_D
#define HIP_PLUGIN_RESAMPLE_DY_D 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_H
#define HIP_PLUGIN_RESAMPLE_DY_H 4
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_W
#define HIP_PLUGIN_RESAMPLE_DY_W 4
#endif

#ifndef HIP_PLUGIN_RESAMPLE_X_STRIDE_N
#define HIP_PLUGIN_RESAMPLE_X_STRIDE_N 64
#endif

#ifndef HIP_PLUGIN_RESAMPLE_X_STRIDE_C
#define HIP_PLUGIN_RESAMPLE_X_STRIDE_C 64
#endif

#ifndef HIP_PLUGIN_RESAMPLE_X_STRIDE_D
#define HIP_PLUGIN_RESAMPLE_X_STRIDE_D 64
#endif

#ifndef HIP_PLUGIN_RESAMPLE_X_STRIDE_H
#define HIP_PLUGIN_RESAMPLE_X_STRIDE_H 8
#endif

#ifndef HIP_PLUGIN_RESAMPLE_X_STRIDE_W
#define HIP_PLUGIN_RESAMPLE_X_STRIDE_W 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_Y_STRIDE_N
#define HIP_PLUGIN_RESAMPLE_Y_STRIDE_N 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_Y_STRIDE_C
#define HIP_PLUGIN_RESAMPLE_Y_STRIDE_C 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_Y_STRIDE_D
#define HIP_PLUGIN_RESAMPLE_Y_STRIDE_D 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_Y_STRIDE_H
#define HIP_PLUGIN_RESAMPLE_Y_STRIDE_H 4
#endif

#ifndef HIP_PLUGIN_RESAMPLE_Y_STRIDE_W
#define HIP_PLUGIN_RESAMPLE_Y_STRIDE_W 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_STRIDE_N
#define HIP_PLUGIN_RESAMPLE_DX_STRIDE_N 64
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_STRIDE_C
#define HIP_PLUGIN_RESAMPLE_DX_STRIDE_C 64
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_STRIDE_D
#define HIP_PLUGIN_RESAMPLE_DX_STRIDE_D 64
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_STRIDE_H
#define HIP_PLUGIN_RESAMPLE_DX_STRIDE_H 8
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_STRIDE_W
#define HIP_PLUGIN_RESAMPLE_DX_STRIDE_W 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_STRIDE_N
#define HIP_PLUGIN_RESAMPLE_DY_STRIDE_N 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_STRIDE_C
#define HIP_PLUGIN_RESAMPLE_DY_STRIDE_C 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_STRIDE_D
#define HIP_PLUGIN_RESAMPLE_DY_STRIDE_D 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_STRIDE_H
#define HIP_PLUGIN_RESAMPLE_DY_STRIDE_H 4
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DY_STRIDE_W
#define HIP_PLUGIN_RESAMPLE_DY_STRIDE_W 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_N
#define HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_N 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_C
#define HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_C 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_D
#define HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_D 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_H
#define HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_H 4
#endif

#ifndef HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_W
#define HIP_PLUGIN_RESAMPLE_INDEX_STRIDE_W 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_WINDOW_D
#define HIP_PLUGIN_RESAMPLE_WINDOW_D 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_WINDOW_H
#define HIP_PLUGIN_RESAMPLE_WINDOW_H 2
#endif

#ifndef HIP_PLUGIN_RESAMPLE_WINDOW_W
#define HIP_PLUGIN_RESAMPLE_WINDOW_W 2
#endif

#ifndef HIP_PLUGIN_RESAMPLE_STRIDE_D
#define HIP_PLUGIN_RESAMPLE_STRIDE_D 1
#endif

#ifndef HIP_PLUGIN_RESAMPLE_STRIDE_H
#define HIP_PLUGIN_RESAMPLE_STRIDE_H 2
#endif

#ifndef HIP_PLUGIN_RESAMPLE_STRIDE_W
#define HIP_PLUGIN_RESAMPLE_STRIDE_W 2
#endif

#ifndef HIP_PLUGIN_RESAMPLE_PRE_PAD_D
#define HIP_PLUGIN_RESAMPLE_PRE_PAD_D 0
#endif

#ifndef HIP_PLUGIN_RESAMPLE_PRE_PAD_H
#define HIP_PLUGIN_RESAMPLE_PRE_PAD_H 0
#endif

#ifndef HIP_PLUGIN_RESAMPLE_PRE_PAD_W
#define HIP_PLUGIN_RESAMPLE_PRE_PAD_W 0
#endif

#ifndef HIP_PLUGIN_RESAMPLE_OUTPUT_ELEMENT_COUNT
#define HIP_PLUGIN_RESAMPLE_OUTPUT_ELEMENT_COUNT 16
#endif

#ifndef HIP_PLUGIN_RESAMPLE_DX_ELEMENT_COUNT
#define HIP_PLUGIN_RESAMPLE_DX_ELEMENT_COUNT 64
#endif
