// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier:  MIT

#ifdef HIPDNN_ENABLE_KERNEL_INGESTOR

#include <algorithm>
#include <cstdint>
#include <map>
#include <set>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include <hipdnn_data_sdk/utilities/PlatformUtils.hpp>
#include <hipdnn_data_sdk/utilities/VersionUtils.hpp>
#include <hipdnn_plugin_sdk/BehaviorNote.h>
#include <hipdnn_plugin_sdk/ingestor/Descriptors.hpp>
#include <hipdnn_plugin_sdk/ingestor/MatchContext.hpp>
#include <hipdnn_plugin_sdk/ingestor/NativeRegistry.hpp>

#include "engines/kernel_ingestor_engine/KernelIngestorEngine.hpp"

/**
 * @file TestGfx950ConvFwdPacks.cpp
 * @brief A census of what hipkernel:Gfx950ConvFwd actually loads, read through
 *        hip_kernel_provider::kernel_ingestor_engine::discoverDescriptorSets(),
 *        which runs the provider's real typed registration before validating and
 *        loading, so a pack whose native symbols do not register drops out here
 *        rather than at first dispatch on a device.
 *
 * The expectations are rendered from the finalized emitted-bundle inventory -- the
 * documents this run wrote, after metadata resolution, the resolved-knob check and
 * engine-wide de-duplication -- not from the authored config, whose pack file stems are
 * not the pack names the loader reports.
 *
 * This file belongs to the census binary, hip_kernel_provider_census_tests, not to the
 * ordinary unit binary: every case below needs a descriptor shard and the census
 * environment. The generated matcher test is the one that stays in
 * hip_kernel_provider_tests.
 *
 * Register one entry with hkp_register_census_tests(), which documents its own
 * arguments, in src/tests/CMakeLists.txt beside hkp_verify_embedded_sources().
 *
 * Generated by IngestorGenerator.
 */
namespace
{

using namespace hip_kernel_provider::kernel_ingestor_engine;
namespace ingestor = hipdnn_plugin_sdk::ingestor;

/// One architecture's row of the emitted inventory.
struct ExpectedInventory
{
    std::set<std::string> packNames;
    std::set<std::string> kernelNames;
};

/// Wildcard key: descriptors naming no architecture ship for every device, so they
/// cannot be filed under a concrete id.
constexpr const char* ARCH_WILDCARD = "*";

/// The emitted inventory, keyed by architecture.
const std::map<std::string, ExpectedInventory>& expectedByArch()
{
    static const std::map<std::string, ExpectedInventory> s_expected = {
        {"gfx950",
         ExpectedInventory{
             {
                 "hipkernel:gfx950_conv_fwd",
             },
             {
                 "gfx950_conv_fwd_dtypebf16_G16_N2_Hi12_Wi12_C16_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G16_N2_Hi12_Wi12_C16_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G24_N2_Hi12_Wi12_C24_K24_Y3_X3_sH1_sW1_pH0_pW0_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G24_N2_Hi12_Wi12_C24_K24_Y3_X3_sH1_sW1_pH0_pW0_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G24_N2_Hi12_Wi12_C24_K24_Y3_X3_sH1_sW1_pH2_pW2_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G24_N2_Hi12_Wi12_C24_K24_Y3_X3_sH1_sW1_pH2_pW2_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G24_N2_Hi13_Wi13_C24_K24_Y3_X3_sH1_sW1_pH2_pW2_dH2_dW2_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G24_N2_Hi13_Wi13_C24_K24_Y3_X3_sH1_sW1_pH2_pW2_dH2_dW2_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G24_N2_Hi13_Wi13_C24_K24_Y3_X3_sH2_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G24_N2_Hi13_Wi13_C24_K24_Y3_X3_sH2_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G2_N2_Hi13_Wi13_C16_K16_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G2_N2_Hi13_Wi13_C16_K16_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G2_N2_Hi15_Wi15_C16_K16_Y5_X5_sH1_sW1_pH4_pW4_dH2_dW2_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G2_N2_Hi15_Wi15_C16_K16_Y5_X5_sH1_sW1_pH4_pW4_dH2_dW2_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G32_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_spatial_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G32_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G32_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G32_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G32_N2_Hi17_Wi17_C32_K32_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_spatial_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G32_N2_Hi17_Wi17_C32_K32_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G32_N2_Hi17_Wi17_C32_K32_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G32_N2_Hi17_Wi17_C32_K32_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G4_N2_Hi11_Wi11_C12_K24_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G4_N2_Hi11_Wi11_C12_K24_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G5_N2_Hi56_Wi24_C5_K5_Y17_X17_sH1_sW1_pH8_pW8_dH1_dW1_"
                 "family1_spatial_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G5_N2_Hi56_Wi24_C5_K5_Y17_X17_sH1_sW1_pH8_pW8_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G5_N2_Hi56_Wi24_C5_K5_Y17_X17_sH1_sW1_pH8_pW8_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G5_N2_Hi9_Wi9_C5_K5_Y7_X7_sH1_sW1_pH3_pW3_dH1_dW1_"
                 "family1_spatial_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G5_N2_Hi9_Wi9_C5_K5_Y7_X7_sH1_sW1_pH3_pW3_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G5_N2_Hi9_Wi9_C5_K5_Y7_X7_sH1_sW1_pH3_pW3_dH1_dW1_tile_"
                 "k128",
                 "gfx950_conv_fwd_dtypebf16_G5_N2_Hi9_Wi9_C5_K5_Y7_X7_sH1_sW1_pH3_pW3_dH1_dW1_tile_"
                 "k64",
                 "gfx950_conv_fwd_dtypebf16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw32_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw32_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi14_Wi14_C96_K96_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw3_bwv2",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi14_Wi14_C96_K96_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi14_Wi14_C96_K96_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi14_Wi14_C96_K96_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi16_Wi18_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi16_Wi18_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi16_Wi18_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi17_Wi17_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi17_Wi17_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_G96_N2_Hi17_Wi17_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_N1_Hi15_Wi17_C32_K32_Y3_X3_sH1_sW1_pH2_pW2_dH2_dW2_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_N1_Hi15_Wi17_C32_K32_Y3_X3_sH1_sW1_pH2_pW2_dH2_dW2_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_N1_Hi8_Wi8_C32_K64_Y1_X1_sH1_sW1_pH0_pW0_dH1_dW1_tile_"
                 "k128",
                 "gfx950_conv_fwd_dtypebf16_N1_Hi8_Wi8_C32_K64_Y1_X1_sH1_sW1_pH0_pW0_dH1_dW1_tile_"
                 "k64",
                 "gfx950_conv_fwd_dtypebf16_N2_Hi11_Wi17_C32_K64_Y3_X5_sH1_sW2_pH1_pW2_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_N2_Hi11_Wi17_C32_K64_Y3_X5_sH1_sW2_pH1_pW2_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypebf16_N2_Hi17_Wi19_C32_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypebf16_N2_Hi17_Wi19_C32_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G16_N2_Hi12_Wi12_C16_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G16_N2_Hi12_Wi12_C16_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G24_N2_Hi12_Wi12_C24_K24_Y3_X3_sH1_sW1_pH0_pW0_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G24_N2_Hi12_Wi12_C24_K24_Y3_X3_sH1_sW1_pH0_pW0_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G24_N2_Hi12_Wi12_C24_K24_Y3_X3_sH1_sW1_pH2_pW2_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G24_N2_Hi12_Wi12_C24_K24_Y3_X3_sH1_sW1_pH2_pW2_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G24_N2_Hi13_Wi13_C24_K24_Y3_X3_sH1_sW1_pH2_pW2_dH2_dW2_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G24_N2_Hi13_Wi13_C24_K24_Y3_X3_sH1_sW1_pH2_pW2_dH2_dW2_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G24_N2_Hi13_Wi13_C24_K24_Y3_X3_sH2_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G24_N2_Hi13_Wi13_C24_K24_Y3_X3_sH2_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G2_N2_Hi13_Wi13_C16_K16_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G2_N2_Hi13_Wi13_C16_K16_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G2_N2_Hi15_Wi15_C16_K16_Y5_X5_sH1_sW1_pH4_pW4_dH2_dW2_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G2_N2_Hi15_Wi15_C16_K16_Y5_X5_sH1_sW1_pH4_pW4_dH2_dW2_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G32_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_spatial_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G32_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G32_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G32_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G32_N2_Hi17_Wi17_C32_K32_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_spatial_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G32_N2_Hi17_Wi17_C32_K32_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G32_N2_Hi17_Wi17_C32_K32_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G32_N2_Hi17_Wi17_C32_K32_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G4_N2_Hi11_Wi11_C12_K24_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G4_N2_Hi11_Wi11_C12_K24_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G5_N2_Hi56_Wi24_C5_K5_Y17_X17_sH1_sW1_pH8_pW8_dH1_dW1_"
                 "family1_spatial_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G5_N2_Hi56_Wi24_C5_K5_Y17_X17_sH1_sW1_pH8_pW8_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G5_N2_Hi56_Wi24_C5_K5_Y17_X17_sH1_sW1_pH8_pW8_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G5_N2_Hi9_Wi9_C5_K5_Y7_X7_sH1_sW1_pH3_pW3_dH1_dW1_"
                 "family1_spatial_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G5_N2_Hi9_Wi9_C5_K5_Y7_X7_sH1_sW1_pH3_pW3_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G5_N2_Hi9_Wi9_C5_K5_Y7_X7_sH1_sW1_pH3_pW3_dH1_dW1_tile_"
                 "k128",
                 "gfx950_conv_fwd_dtypefp16_G5_N2_Hi9_Wi9_C5_K5_Y7_X7_sH1_sW1_pH3_pW3_dH1_dW1_tile_"
                 "k64",
                 "gfx950_conv_fwd_dtypefp16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw32_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw32_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G64_N2_Hi70_Wi40_C64_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi14_Wi14_C96_K96_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw3_bwv2",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi14_Wi14_C96_K96_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi14_Wi14_C96_K96_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi14_Wi14_C96_K96_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi16_Wi18_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi16_Wi18_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi16_Wi18_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi17_Wi17_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "family1_std_bw4_bwv1",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi17_Wi17_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_G96_N2_Hi17_Wi17_C96_K96_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_N1_Hi15_Wi17_C32_K32_Y3_X3_sH1_sW1_pH2_pW2_dH2_dW2_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_N1_Hi15_Wi17_C32_K32_Y3_X3_sH1_sW1_pH2_pW2_dH2_dW2_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_N1_Hi8_Wi8_C32_K64_Y1_X1_sH1_sW1_pH0_pW0_dH1_dW1_tile_"
                 "k128",
                 "gfx950_conv_fwd_dtypefp16_N1_Hi8_Wi8_C32_K64_Y1_X1_sH1_sW1_pH0_pW0_dH1_dW1_tile_"
                 "k64",
                 "gfx950_conv_fwd_dtypefp16_N2_Hi11_Wi17_C32_K64_Y3_X5_sH1_sW2_pH1_pW2_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_N2_Hi11_Wi17_C32_K64_Y3_X5_sH1_sW2_pH1_pW2_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_N2_Hi14_Wi14_C32_K32_Y3_X3_sH1_sW1_pH1_pW1_dH1_dW1_"
                 "tile_k64",
                 "gfx950_conv_fwd_dtypefp16_N2_Hi17_Wi19_C32_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k128",
                 "gfx950_conv_fwd_dtypefp16_N2_Hi17_Wi19_C32_K64_Y3_X3_sH2_sW2_pH1_pW1_dH1_dW1_"
                 "tile_k64",
             },
         }},
    };
    return s_expected;
}

/// The runtime source kind every kernel must declare at the loader. A packaged bundle
/// is lowered to a kpack archive first, so the authored builder kind is not what
/// arrives.
constexpr ingestor::KernelSourceKind EXPECTED_SOURCE_KIND = ingestor::KernelSourceKind::KPACK;

/// A pack or kernel naming no architecture inherits/wildcards; one that names
/// architectures must name the requested one, or this is the wrong shard.
bool coversArch(const std::vector<std::string>& declared, const std::string& arch)
{
    return declared.empty() || std::find(declared.begin(), declared.end(), arch) != declared.end();
}

class TestGfx950ConvFwdPacks : public ::testing::Test
{
protected:
    void SetUp() override
    {
        _arch = hipdnn_data_sdk::utilities::getEnv("HIPDNN_TEST_EXPECTED_ARCH");
        ASSERT_FALSE(_arch.empty())
            << "HIPDNN_TEST_EXPECTED_ARCH is unset, so this census has no expectation to "
               "check against. The architecture is supplied explicitly by the caller; it "
               "is never detected from a device and never taken from the descriptors "
               "being censused.";

        const auto& table = expectedByArch();
        auto row = table.find(_arch);
        if(row == table.end())
        {
            row = table.find(ARCH_WILDCARD);
        }
        ASSERT_NE(row, table.end())
            << "this bundle emitted no descriptors for architecture '" << _arch
            << "' and no architecture-independent ones either, so there is no expected "
               "identity to check. Either the wrong architecture was requested or the "
               "generation that produced this bundle did not cover it.";
        _expected = &row->second;

        const auto& sets = discoverDescriptorSets();
        const auto match = std::find_if(sets.begin(), sets.end(), [](const auto& set) {
            return set.engine.name == "hipkernel:Gfx950ConvFwd";
        });
        ASSERT_NE(match, sets.end())
            << "descriptor set 'hipkernel:Gfx950ConvFwd' did not load. Either its "
               "descriptors were never installed under the tree this binary reads, or "
               "its pack failed to register its native symbols and every descriptor "
               "naming one of them was dropped.";
        _set = &*match;
    }

    std::string _arch;
    const ExpectedInventory* _expected = nullptr;
    const ingestor::DescriptorSet* _set = nullptr;
};

TEST_F(TestGfx950ConvFwdPacks, LoadsExactlyTheEmittedPacks)
{
    std::set<std::string> loaded;
    for(const auto& pack : _set->packs)
    {
        loaded.insert(pack.name);
    }
    // Set equality, not a count: a missing pack and an extra one cancel in a count.
    EXPECT_EQ(loaded, _expected->packNames);
}

TEST_F(TestGfx950ConvFwdPacks, LoadsExactlyTheEmittedKernels)
{
    std::set<std::string> loaded;
    for(const auto& pack : _set->packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            loaded.insert(kernel.name);
        }
    }
    EXPECT_EQ(loaded, _expected->kernelNames);
}

TEST_F(TestGfx950ConvFwdPacks, EveryLoadedDescriptorCoversTheRequestedArch)
{
    for(const auto& pack : _set->packs)
    {
        EXPECT_TRUE(coversArch(pack.arch, _arch))
            << "pack '" << pack.name << "' does not cover '" << _arch
            << "', so this is not that architecture's shard";
        for(const auto& kernel : pack.kernels)
        {
            EXPECT_TRUE(coversArch(kernel.arch, _arch))
                << "kernel '" << kernel.name << "' does not cover '" << _arch << "'";
        }
    }
}

TEST_F(TestGfx950ConvFwdPacks, EveryKernelDeclaresTheEmittedRuntimeSourceKind)
{
    for(const auto& pack : _set->packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            EXPECT_EQ(kernel.source.kind, EXPECTED_SOURCE_KIND)
                << "kernel '" << kernel.name << "' reached the loader as a different "
                << "source kind than this bundle ships";
        }
    }
}

TEST_F(TestGfx950ConvFwdPacks, DeclaresTheConfiguredSdkVersion)
{
    EXPECT_EQ(_set->engine.sdkVersion, hipdnn_data_sdk::utilities::Version{std::string("1.0.0")});
}

TEST_F(TestGfx950ConvFwdPacks, ExposesTheConfiguredKnobs)
{
    ASSERT_EQ(_set->engine.knobs.size(), 2U);
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "tile_k"),
              _set->engine.knobs.end());
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "kernel_family"),
              _set->engine.knobs.end());
}

/// The engine ships a ranking model, so its score symbol must be REGISTERED, not merely
/// named: a descriptor naming an unregistered one is dropped, and the engine then ranks
/// on priority as if no model existed.
TEST_F(TestGfx950ConvFwdPacks, RanksThroughItsRegisteredScoreSymbol)
{
    ASSERT_TRUE(_set->heuristic.has_value());
    EXPECT_EQ(_set->heuristic->payload, "hipkernel.gfx950_conv_fwd.score");
    EXPECT_TRUE(ingestor::ScoreRegistry::isRegistered("hipkernel.gfx950_conv_fwd.score"));
}

/// UMD policy, this engine's shape: a SINGLE-pack engine carries no graph-scoped
/// criterion -- its own graph_match admits the node type and validates shape. Mirrors
/// TestConvFwdPack.cpp's HasAGraphMatchAndOneKernelMatcher.
TEST_F(TestGfx950ConvFwdPacks, CarriesNoGraphScopedMatcher)
{
    EXPECT_FALSE(_set->engine.graphMatchNativeSymbol.empty());
    const auto graphScoped
        = std::count_if(_set->matchers.begin(), _set->matchers.end(), [](const auto& matcher) {
              return matcher.scope == ingestor::MatchScope::GRAPH;
          });
    EXPECT_EQ(graphScoped, 0);
}

TEST_F(TestGfx950ConvFwdPacks, CarriesExactlyOneSharedKernelScopedMatcher)
{
    const auto kernelScoped
        = std::count_if(_set->matchers.begin(), _set->matchers.end(), [](const auto& matcher) {
              return matcher.scope == ingestor::MatchScope::KERNEL;
          });
    EXPECT_EQ(kernelScoped, 1);
}

} // namespace

#endif // HIPDNN_ENABLE_KERNEL_INGESTOR
